# Numpy Problems
---

## Find primes numbers between 1 and 1000, ( use only numpy array, slicing, masking etc. )

### Notes

numpy has __vectorize__ function just like __map__ python function

```python
import numpy as np

vfunc = np.vectorize(lambda x, y: x % y == 0)

vfunc(np.array([2, 3, 4, 5, 6, 7]), 2)

>>> np.array([True, False, True, False, True, False])
```

Above example vfunc returns array, *vfunc is much like np.sin/np.cos etc*


```python
def sum(a, b):
    return a + b

lambda a, b: a + b
```

**reduce**
```python

np.add.reduce(np.array([1, 2, 3]))
>>> 6
```

In [1]:
import numpy as np

In [3]:
np.add(np.array([1, 2, 3]), 2)

array([3, 4, 5])

In [4]:
np.array([1, 2, 3]) + 2

array([3, 4, 5])

In [5]:
np.add.reduce(np.array([1, 2, 3]))

6

#### any and all

In [6]:
np.any(np.array([True, False, True]))

True

In [8]:
np.all(np.array([True, False, True]))

False

In [9]:
np.all(np.array([True, True, True]))

True

In [10]:
np.all(np.array([False, False, False]))

False

In [11]:
np.all(~np.array([False, False, False]))

True

In [13]:
not np.all(np.array([False, False, False]))

True

In [14]:
~np.array([False, False, False])

array([ True,  True,  True], dtype=bool)

In [15]:
np.all(np.array([False, True, False]))

False

In [16]:
not np.all(np.array([False, True, False]))

True

In [17]:
np.all(~np.array([False, True, False]))

False

[https://projecteuler.net/problem=25](https://projecteuler.net/problem=25)

1000-digit Fibonacci number

Note:

In [18]:
len(list(str(12786543)))

8

In [19]:
len(str(128764835))

9

In [20]:
int(np.log10(128764835) + 1)

9

In [35]:
np.info(np.log10)

log10(x[, out])

Return the base 10 logarithm of the input array, element-wise.

Parameters
----------
x : array_like
    Input values.

Returns
-------
y : ndarray
    The logarithm to the base 10 of `x`, element-wise. NaNs are
    returned where x is negative.

See Also
--------
emath.log10

Notes
-----
Logarithm is a multivalued function: for each `x` there is an infinite
number of `z` such that `10**z = x`. The convention is to return the
`z` whose imaginary part lies in `[-pi, pi]`.

For real-valued input data types, `log10` always returns real output.
For each value that cannot be expressed as a real number or infinity,
it yields ``nan`` and sets the `invalid` floating point error flag.

For complex-valued input, `log10` is a complex analytical function that
has a branch cut `[-inf, 0]` and is continuous from above on it.
`log10` handles the floating-point negative zero as an infinitesimal
negative number, conforming to the C99 standard.

References
----------
.. [1] M. Abramowit

In [36]:
np.log10([567])

array([ 2.75358306])

In [33]:
b = np.float64(567)
b.log10

AttributeError: 'numpy.float64' object has no attribute 'log10'

In [28]:
np.log10(1287648359798234792387492384923849243)

AttributeError: 'int' object has no attribute 'log10'

In [23]:
np.log10(np.float64(1287648359798234792387492384923849243))

36.109797278979038

In [24]:
np.int64

numpy.int64

In [27]:
np.log10(np.float64(29348792384921384792384921387492834928374928734928734928734928734928734987234987234987239487293487293487293847))

109.46759023603151

In [37]:
arr = np.array([1, 2])

In [38]:
np.info(np.append)

 append(arr, values, axis=None)

Append values to the end of an array.

Parameters
----------
arr : array_like
    Values are appended to a copy of this array.
values : array_like
    These values are appended to a copy of `arr`.  It must be of the
    correct shape (the same shape as `arr`, excluding `axis`).  If
    `axis` is not specified, `values` can be any shape and will be
    flattened before use.
axis : int, optional
    The axis along which `values` are appended.  If `axis` is not
    given, both `arr` and `values` are flattened before use.

Returns
-------
append : ndarray
    A copy of `arr` with `values` appended to `axis`.  Note that
    `append` does not occur in-place: a new array is allocated and
    filled.  If `axis` is None, `out` is a flattened array.

See Also
--------
insert : Insert elements into an array.
delete : Delete elements from an array.

Examples
--------
>>> np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
array([1, 2, 3, 4, 5, 6, 7, 8, 9])

When `axis` is

In [39]:
arr[-2:]

array([1, 2])

In [43]:
arr = np.append(arr, np.sum(arr[-2:]))

In [44]:
arr = np.append(arr, np.sum(arr[-2:]))

In [45]:
arr

array([1, 2, 3, 5])

In [46]:
arr = np.append(arr, np.sum(arr[-2:]))

In [47]:
arr

array([1, 2, 3, 5, 8])

In [51]:
arr = np.array([1, 2])

In [52]:
arr = np.array([arr[-1], np.sum(arr)])

In [53]:
arr

array([2, 3])

In [55]:
arr = np.array([1, 2])
while np.log10(np.float64(arr[-1])) < 10:
    arr = np.array([arr[-1], np.sum(arr)])
print(arr)

[ 7778742049 12586269025]
