# Numpy
---

Numerical Processing library

> NumPy (pronounced "Numb Pie" or sometimes "Numb pee") is an extension to the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. - Wikipedia

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.1'

## Arrays

*Create a new array*

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

*Array are generally can be considered as Matrices*

$$
\begin{bmatrix}
    1 & 2 & 3
\end{bmatrix}
$$

**Multidimensional array**

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

*can be more visually seen as*

$$
\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6
\end{bmatrix}
$$

In [6]:
b = np.array([4, 5, 6])

In [7]:
b

array([4, 5, 6])

## Array Operations

*Adding two matrices*

In [8]:
a + b

array([5, 7, 9])

> *Result: * $[1+4, 2+5, 3+6]$

*Adding a scalar to matrix*

In [9]:
a + 1

array([2, 3, 4])

*Dividing*

In [10]:
b / a

array([ 4. ,  2.5,  2. ])

In [11]:
b // a

array([4, 2, 2])

> *Result: * $[4\div1, 5\div2, 6\div3]$

*Dividing by a scalar*

In [12]:
b / 2

array([ 2. ,  2.5,  3. ])

In [13]:
b // 2

array([2, 2, 3])

> Division is default python behavior

*Multiplying by scalar*

In [14]:
b * 3

array([12, 15, 18])

*Multiplying two array*

In [15]:
a * b

array([ 4, 10, 18])

> *Result is * $[1*4, 2*5, 3*6]$

> *Remember operations between arrays is element wise, It is not the matrix multiplication ( vector product )*


*Dot Product*

In [16]:
a.dot(b)

32

In [18]:
# only works in python 3.5 and above
a @ b

32

### Array attributes

In [19]:
type(a)

numpy.ndarray

*datatype of a array*

In [20]:
a.dtype

dtype('int64')

> This means that all the elements are of type int64.

*Note: Numpy array elements are of single types unlike of multitype of list*

*Size: total number of items in array*

In [21]:
a.size

3

In [23]:
a

array([1, 2, 3])

In [24]:
c.size

6

In [25]:
c

array([[1, 2, 3],
       [4, 5, 6]])

*len is different than size*

In [26]:
len(c)

2

> `c` is multidimensional array with 2 rows and 3 columns, `len` gave length of rows

*Shape: shape of array*

In [27]:
a.shape

(3,)

> *length of a along first dimension, which is only `a` has*

In [28]:
c.shape

(2, 3)

> *shape always returns a tuple*

> *shape of array is length of array, in each dimension*



In [29]:
np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]).shape

(3, 3)

*shape of a three dimensional array*

In [30]:
np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]).shape

(2, 2, 3)

*Dimension of array*

In [31]:
a.ndim

1

In [32]:
b.ndim

1

In [33]:
c.ndim

2

**Array with floating types or unicode types**

In [34]:
d = np.array([1.0, 2, 4, 9])
d

array([ 1.,  2.,  4.,  9.])

> *All the other integer items are converted to float*

In [35]:
d.dtype

dtype('float64')

In [36]:
e = np.array(['a', 'b', 'c', 'd'])
e

array(['a', 'b', 'c', 'd'], 
      dtype='<U1')

In [37]:
e.dtype

dtype('<U1')

*Size of array items in bytes*

In [39]:
a

array([1, 2, 3])

In [40]:
# int64
a.itemsize

8

In [41]:
# float64
d.itemsize

8

In [42]:
# <U1
e.itemsize

4

*Memory usage of array*

In [43]:
e.nbytes

16

*Which is same as*

In [44]:
e.itemsize * e.size

16

In [45]:
a.nbytes

24

### Array Indexing

In [46]:
a

array([1, 2, 3])

*Working with array index is "similar" to list index*

In [47]:
# select first element
a[0]

1

In [48]:
# select last element
a[-1]

3

In [49]:
# assign a new value to particular index
a[1] = 7

In [50]:
a

array([1, 7, 3])

*fill into array*

In [51]:
b.fill(0)

In [52]:
b

array([0, 0, 0])

**Type cohersion**

In [53]:
a.dtype

dtype('int64')

In [54]:
a[0] = 2.3

In [55]:
a

array([2, 7, 3])

In [56]:
a[0] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

> *Since, a is of dtype int64. 2.3 is cast to int above*

*cannot change dtype of an ndarray*

In [57]:
b.fill(1.1)

In [58]:
b

array([1, 1, 1])

In [59]:
b.astype(np.float64)

array([ 1.,  1.,  1.])

In [60]:
b.dtype

dtype('int64')

> *Same goes for fill*

### Array slicing

**array[lower:upper:step]**

- `lower` if ommitted defaults to 0
- `upper` if ommitted defaults to length of array
- `step`  if ommitted defaults to 1 

In [61]:
a

array([2, 7, 3])

In [62]:
a[:]

array([2, 7, 3])

In [63]:
a[0:]

array([2, 7, 3])

In [64]:
a[:-1]

array([2, 7])

In [65]:
a[:2]

array([2, 7])

In [66]:
a[1:]

array([7, 3])

In [67]:
a[::2]

array([2, 3])

In [68]:
a[::-1]

array([3, 7, 2])

In [69]:
a[-2:]

array([7, 3])

**Cool tricks with array slicing**

*finding out mid point of every consecutive items in an array*

In [70]:
aa = np.array([1, 2, 3, 5, 8, 13, 21, 34])

In [71]:
aa[1:]

array([ 2,  3,  5,  8, 13, 21, 34])

In [72]:
aa[:-1]

array([ 1,  2,  3,  5,  8, 13, 21])

In [73]:
aa[1:] + aa[:-1]

array([ 3,  5,  8, 13, 21, 34, 55])

In [74]:
(aa[1:] + aa[:-1]) / 2

array([  1.5,   2.5,   4. ,   6.5,  10.5,  17. ,  27.5])

### Creating arrays

*create an empty array*

In [75]:
np.empty(3)

array([  1.48219694e-323,   3.45845952e-323,   9.88131292e-324])

*array of zeros*

In [76]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [77]:
np.zeros((3,))

array([ 0.,  0.,  0.])

In [78]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [79]:
np.zeros((2, 2, 3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

*array of ones*

In [80]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

*from range*

In [81]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])


*Random Numbers*

In [82]:
np.random.rand(3)

array([ 0.46818697,  0.68337817,  0.36534436])