# Numpy
---

Numerical Processing library

In [1]:
import numpy as np

**Random Numbers**

In [2]:
np.random.rand(9)

array([ 0.21188656,  0.83753858,  0.14354644,  0.60110621,  0.53970442,
        0.7783575 ,  0.22259319,  0.76635527,  0.48352254])

In [3]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [4]:
np.random.randint(1, 99)

61

In [5]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 'absolute_import',
 'bench',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings

In [6]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    Parameters
    ----------
    low : float, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float
        Upper boundary of the output interval.  All values generated will be
        less than high.  The default value is 1.0.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
   

In [7]:
np.random.uniform(1, 20, 10)

array([ 11.25671401,  13.89222383,   2.42210436,  18.40851448,
         5.8731096 ,  13.68666102,   6.08726566,  16.10977246,
         5.22332538,  15.8852688 ])

**Array**

In [8]:
arr = np.array([2, 5, 6, 9, 10])

In [9]:
arr

array([ 2,  5,  6,  9, 10])

In [10]:
arr.size

5

In [11]:
arr.ndim

1

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr.shape

(5,)

In [14]:
arr2 = np.array([[1, 2, 3], [8, 9, 7]])

In [15]:
arr2.shape

(2, 3)

In [16]:
arr2.size

6

In [17]:
arr2.ndim

2

In [18]:
arr

array([ 2,  5,  6,  9, 10])

In [19]:
arr * 3

array([ 6, 15, 18, 27, 30])

In [20]:
arr + 4

array([ 6,  9, 10, 13, 14])

In [21]:
arr + (arr + 2)

array([ 6, 12, 14, 20, 22])

In [22]:
arr2 * 3

array([[ 3,  6,  9],
       [24, 27, 21]])

In [24]:
np.array([1.2, 4, 9, 5, 0])

array([ 1.2,  4. ,  9. ,  5. ,  0. ])

In [25]:
np.array([1.2, 4, 9, 5, 0]).dtype

dtype('float64')

In [26]:
np.array(['1', 7, 9, 2.3])

array(['1', '7', '9', '2.3'], 
      dtype='<U3')

In [27]:
np.array(['1', 7, 9, 2.3]) * 3

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U3') dtype('<U3') dtype('<U3')

In [28]:
lst = [x for x in range(0, 99)]

In [31]:
%timeit [x*3 for x in lst]

100000 loops, best of 3: 8.57 µs per loop


In [32]:
arr_lst = np.array(lst)

In [33]:
%timeit arr_lst * 3

The slowest run took 29.03 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.78 µs per loop


In [34]:
dir(arr2)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__r

In [35]:
arr2

array([[1, 2, 3],
       [8, 9, 7]])

In [36]:
help(arr2.all)

Help on built-in function all:

all(...) method of numpy.ndarray instance
    a.all(axis=None, out=None, keepdims=False)
    
    Returns True if all elements evaluate to True.
    
    Refer to `numpy.all` for full documentation.
    
    See Also
    --------
    numpy.all : equivalent function



In [37]:
arr2.all()

True

In [38]:
np.array([1, 0, 9]).all()

False

In [39]:
arr2

array([[1, 2, 3],
       [8, 9, 7]])

In [40]:
arr3 = np.array([[1, 0, 9], [2, 6, 7]])

In [41]:
arr3.all()

False

In [42]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [43]:
arr3.all(axis=0)

array([ True, False,  True], dtype=bool)

In [44]:
arr3.all(axis=1)

array([False,  True], dtype=bool)

In [45]:
help(arr3.cumsum)

Help on built-in function cumsum:

cumsum(...) method of numpy.ndarray instance
    a.cumsum(axis=None, dtype=None, out=None)
    
    Return the cumulative sum of the elements along the given axis.
    
    Refer to `numpy.cumsum` for full documentation.
    
    See Also
    --------
    numpy.cumsum : equivalent function



In [46]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [47]:
arr3.cumsum()

array([ 1,  1, 10, 12, 18, 25])

In [48]:
arr3.cumsum(axis=0)

array([[ 1,  0,  9],
       [ 3,  6, 16]])

In [49]:
arr3.cumsum(axis=1)

array([[ 1,  1, 10],
       [ 2,  8, 15]])

In [50]:
help(arr3.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [51]:
arr3.mean()

4.166666666666667

In [52]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [53]:
arr3.min()

0

In [54]:
arr3.max()

9

In [55]:
np.median(arr3)

4.0

In [56]:
arr3.std()

3.337497399083464

**Matrix**

In [57]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [58]:
help(arr3.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function



In [59]:
arr3.shape

(2, 3)

In [60]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [62]:
arr3.reshape((6,))

array([1, 0, 9, 2, 6, 7])

In [63]:
(6)

6

In [64]:
(6,)

(6,)

In [65]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [66]:
arr3.reshape((3, 2))

array([[1, 0],
       [9, 2],
       [6, 7]])

In [67]:
help(arr3.transpose)

Help on built-in function transpose:

transpose(...) method of numpy.ndarray instance
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    For a 1-D array, this has no effect. (To change between column and
    row vectors, first cast the 1-D array into a matrix object.)
    For a 2-D array, this is the usual matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided and
    ``a.shape = (i[0], i[1], ... i[n-2], i[n-1])``, then
    ``a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])``.
    
    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints
    
     * None or no argument: reverses the order of the axes.
    
     * tuple of ints: `i` in the `j`-th place in the tuple means `a`'s
       `i`-th axis becomes `a.transpose()`'s `j`-th axis.
    
     * `n` ints: same as an n-tuple of the same ints (this form is
       intended simply as

In [68]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [70]:
arr3.transpose()

array([[1, 2],
       [0, 6],
       [9, 7]])

In [ ]:
numpy.fft

In [ ]:
from numpy import fft, f2py

In [ ]:
fft

In [ ]:
f2py

In [ ]:
from numpy.linalg import linalg

In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 3])

In [ ]:
np.array([1, 'a'])

In [ ]:
b = np.array([1, 4, 7])

In [ ]:
dir(b)

In [ ]:
b.dtype

In [ ]:
np.array([1.2, 4.5]).dtype

In [ ]:
b.size

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
a = np.array([[1, 2, 3], [3, 4, 5]])

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
help(a)

In [ ]:
a

In [ ]:
np.arange(2, 9)

In [ ]:
b

In [ ]:
[x*2 for x in b]

In [ ]:
b*2

In [ ]:
%timeit [x*2 for x in range(1, 99)]

In [ ]:
%timeit np.arange(1, 99)*2

In [ ]:
np.ones((3, 2), dtype=np.int64)

In [ ]:
np.zeros((3, 2))

In [ ]:
np.diag(np.arange(2, 7))

In [ ]:
np.diag(np.array([1, 5, 8, 9]))

In [ ]:
np.diag(np.ones(3, dtype=np.int64))

In [ ]:
help(np.empty)

In [ ]:
np.empty([2, 4])

In [ ]:
aa = np.array([[1, 3, 5], [4, 6, 9]])

In [ ]:
aa

In [ ]:
bb = np.array([[1, 3, 5], [4, 6, 9]])

In [ ]:
aa + bb

In [ ]:
np.array([[1, 3, 5], [4, 6, 9]]) + np.array([[1, 3, 5], [4, 6, 9, 8, 0]])

In [ ]:
np.array([[1, 3, 5], [4, 6, 9]]) + np.array([[1, 3, 5], [4, 6, 9,], [5, 6, 7]])

In [ ]:
aa * bb

In [ ]:
aa @ bb

In [ ]:
%matplotlib inline

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
ln = np.linspace(1, 5)

In [ ]:
ln.size

In [ ]:
np.linspace(1, 5, num=10)

In [ ]:
x = np.linspace(0, 20, 10)
y = np.random.randint(0, 20, 10)

In [ ]:
y = np.random.randint

In [ ]:
y = np.random

In [ ]:
y

In [ ]:
plt.plot(x, y)

In [ ]:
np.random.randint?

In [ ]:
aa

In [ ]:
aa[0,0:2]

In [ ]:
aa[1,0:2]

In [ ]:
aa[(1,),(1,)]

In [ ]:
a = numpy.arange(1, 9)

In [ ]:
b = numpy.arange(11, 19)

In [ ]:
a

In [ ]:
b

In [ ]:
a * b

In [ ]:
a + b

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
b = np.array([[2, 3, 4], [2, 4, 7]])

In [ ]:
a.dot(b)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 3, 4])

In [ ]:
a == b

In [ ]:
np.all(np.array([True, False, False]))

In [ ]:
np.any(np.array([True, False, False]))

In [ ]:
aa = np.linspace(1, 9)

In [ ]:
aa

In [ ]:
aa.mean()

In [ ]:
np.median(aa)

In [ ]:
dir(aa)

In [ ]:
aa.std()

In [ ]:
aa.min()

In [ ]:
aa.max()

In [ ]:
aa.transpose()

In [ ]:
abc = np.array([[1, 3, 4], [2, 3, 4]])

In [ ]:
abc.transpose()

In [ ]:
import numpy as np

In [ ]:
np.ravel?

In [ ]:
np.ravel([[2, 3, 4], [3, 4, 5]], 'F')