# Numpy II
---

In [1]:
import numpy as np

In [2]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is inferred
        from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the elements
        into the reshaped array using this index order.  'C' means to
        read / write the elements using C-like index order, with the last axis
        index changing fastest, back to the first axis index changing slowest.
        'F' means to read / write the elements using Fortran-like index order,
        with the firs

In [3]:
np.arange(12).shape

(12,)

In [4]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

*reshapes one array to another with given dimension in row, column format*

In [9]:
np.arange(12).reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [10]:
arr = np.arange(12).reshape(3, 4)

In [11]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Indexing

In [12]:
arr[0]

array([0, 1, 2, 3])

In [13]:
arr[0][-1]

3

*Numpy has another syntax for accessing multidimensional array more elegantly*

`arr[row, column]`

In [14]:
arr[0, -1]

3

> *Which is same as `arr[0][-1]`*

In [15]:
arr[-1, -1]

11

### Slicing

In [16]:
# get all items from 3rd row
arr[2]

array([ 8,  9, 10, 11])

In [17]:
# get all items from 3rd row
arr[2, :]

array([ 8,  9, 10, 11])

In [18]:
# get all items from 3rd row except first
arr[2, 1:]

array([ 9, 10, 11])

In [19]:
# get all items from 3rd row except last
arr[2, :-1]

array([ 8,  9, 10])

In [21]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# get all items from 2nd column
arr[:, 1]

array([1, 5, 9])

In [24]:
# get all items from 2nd column except first
arr[1:, 0]

array([4, 8])

In [25]:
# get all items from 2nd column except last
arr[:-1, 1]

array([1, 5])

In [26]:
# get 2nd and 3rd column items from 2nd and 3rd row
arr[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

### Assigning values to array

In [27]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr[0, 0] = 20

In [29]:
arr

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr[1, 1:]

array([5, 6, 7])

In [31]:
arr[1, 1:] = [55, 66, 77]

In [32]:
arr

array([[20,  1,  2,  3],
       [ 4, 55, 66, 77],
       [ 8,  9, 10, 11]])

In [33]:
arr[1:3, 1:3] = [[555, 666], [999, 100]]

In [34]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 666,  77],
       [  8, 999, 100,  11]])

**slices are references**

In [35]:
ab = arr[1, 2:]

In [36]:
ab

array([666,  77])

In [37]:
ab[0] = 667

In [38]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

> *`667` is reflected on `arr`, because `ab` is just a reference to slice of `arr`*

### Three dimensional array

In [39]:
arr3 = np.arange(24).reshape(2, 3, 4)
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

> *`depth, rows, columns`*

**Indexing**

`arr3[depth, row, column]`

In [40]:
arr3[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
arr3[1, 0]

array([12, 13, 14, 15])

In [42]:
arr3[1, 0, 3]

15

**slicing**

In [43]:
arr3[1, 1:, :-1]

array([[16, 17, 18],
       [20, 21, 22]])

In [44]:
arr3[:, 1:, :-1]

array([[[ 4,  5,  6],
        [ 8,  9, 10]],

       [[16, 17, 18],
        [20, 21, 22]]])

### Fancy Indexing

In [45]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [46]:
# select 2nd and 3rd row
arr[[1, 2]]

array([[  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [47]:
# select 1st, 3rd and 4th item of 2nd row
arr[1, [0, 2, 3]]

array([  4, 667,  77])

In [51]:
# select 1st and 4th item of 2nd and 3rd column respectively
arr[[0, -1], [0, -1]]

array([20, 11])

In [53]:
arr[::2, [0, -1]]

array([[20,  3],
       [ 8, 11]])

### Boolean operation and Masking

In [54]:
abc = np.arange(30)
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
abc < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)

> *gives us boolean array, with True on each element which satifies the condition*

*Only select that satisfy condition*

In [56]:
abc[abc < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
abc[(abc < 10) | (abc > 20)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

use __&__ for "_and_", __|__ for "_or_". Each condition must be enclosed in brackets*

*each condition should be enclosed in brackets, to remove ambiguity created by operator precedence*

In [58]:
abc[abc % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## Numpy Methods

In [59]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
# sum of all elements
abc.sum()

435

In [61]:
# product
abc.prod()

0

In [62]:
abc[(abc > 1) & (abc < 10)].prod()

362880

In [63]:
# mean
abc.mean()

14.5

In [64]:
# median
np.median(abc)

14.5

In [65]:
# maximum
abc.max()

29

In [66]:
# minimum
abc.min()

0

In [67]:
# standard deviation
abc.std()

8.6554414483991895

In [68]:
# variance
abc.var()

74.916666666666671

In [69]:
# cumulative sum
abc.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325,
       351, 378, 406, 435])

In [70]:
# index of minimum value
abc.argmin()

0

In [71]:
# index of maximum value
abc.argmax()

29

**argmin/argmax in multidimensional array**

In [72]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [73]:
# index of minimum value as if given array is flat
arr.argmin()

1

In [74]:
np.unravel_index(arr.argmin(), arr.shape)

(0, 1)

In [75]:
help(np.unravel_index)

Help on built-in function unravel_index in module numpy.core.multiarray:

unravel_index(...)
    unravel_index(indices, dims, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``dims``. Before version 1.6.0,
        this function accepted just one index value.
    dims : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
        array.
    
    See Also
    --------
    ravel_multi_index
    

In [77]:
np.unravel_index(6, arr.shape)

(1, 2)

In [81]:
np.unravel_index(6, (4, 2))

(3, 0)

> return tuple is index within multidimensional array, ie. 0th row and 1st column

*sum across rows or across columns*

In [85]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [82]:
# across rows
arr.sum(axis=0)

array([  32, 1555,  769,   91])

In [83]:
# across columns
arr.sum(axis=1)

array([  26, 1303, 1118])

*can be used with other methods as well*

In [84]:
arr.mean(axis=1)

array([   6.5 ,  325.75,  279.5 ])