# Numpy ( contd...)
---

In [1]:
import numpy as np

In [4]:
arr = np.arange(10, 39)

In [5]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [6]:
arr[0]

10

In [7]:
arr[6]

16

In [8]:
arr[-1]

38

In [10]:
arr[12]

22

In [11]:
arr[12] = 78

In [12]:
arr[12]

78

In [13]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 78, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [15]:
arr.size

29

In [16]:
arr[0:2]

array([10, 11])

In [18]:
arr[0:2] = np.array([10, 9])

In [19]:
arr[0:2]

array([10,  9])

In [20]:
arr[0:2] = 34

In [21]:
arr[0:2]

array([34, 34])

**Multidimensional Array **

*Numpy created a object type array when number of columns are not equal*

In [40]:
arr2 = np.array([np.arange(1, 9), np.arange(91, 99)])

In [41]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [91, 92, 93, 94, 95, 96, 97, 98]])

In [42]:
arr2.shape

(2, 8)

In [52]:
arr2.size

16

In [45]:
arr3 = np.array([[2, 3, 4, 5, 6], [4, 7, 8, 9, 8]])

In [46]:
arr3.dtype

dtype('int64')

In [47]:
arr3.shape

(2, 5)

In [48]:
arr3.size

10

In [49]:
arr3

array([[2, 3, 4, 5, 6],
       [4, 7, 8, 9, 8]])

In [50]:
arr3.dtype

dtype('int64')

In [51]:
arr3.astype(np.float64)

array([[ 2.,  3.,  4.,  5.,  6.],
       [ 4.,  7.,  8.,  9.,  8.]])

In [36]:
np.array([[3, 4, 5, 9], [9,8,7, 6]]).dtype

dtype('int64')

In [53]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [91, 92, 93, 94, 95, 96, 97, 98]])

In [54]:
arr2[0]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
arr[0][1]

IndexError: invalid index to scalar variable.

![](http://memory.osu.edu/classes/python/_images/numpy_indexing.png)

In [59]:
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [91, 92, 93, 94, 95, 96, 97, 98]])

`arr[row, col]`

In [65]:
arr2[0, 0]

1

In [66]:
arr2[0, 6]

7

In [68]:
arr2[0, 2:4]

array([3, 4])

In [69]:
arr4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [70]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [71]:
arr4[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
arr4[:, 2]

array([ 3,  6,  9, 12])

In [75]:
arr4[::2, ::2]

array([[1, 3],
       [7, 9]])

In [76]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
arr4[-1]

array([10, 11, 12])

In [78]:
arr4[-1, -1]

12

In [79]:
arr4[-3]

array([4, 5, 6])

In [80]:
arr4[-3:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
arr4[2, 2] = 19

In [85]:
arr4[2, 2]

19

In [87]:
arr4[2:, 2]

array([19, 12])

In [88]:
arr4[2:, 2] = [18, 17]

In [89]:
arr4[2:, 2]

array([18, 17])

In [90]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 18],
       [10, 11, 17]])

In [104]:
arr4[2:, 2:]

array([[18],
       [17]])

In [105]:
arr4[2:, 2:] = [[19], [22]]

In [106]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 19],
       [10, 11, 22]])

In [92]:
arr6

array([ 8, 11])

In [101]:
arr6[0]

19

In [102]:
arr6[0] = 19

In [103]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 18],
       [10, 11, 17]])

In [ ]:
arr4[]

In [93]:
arr6 = np.array([19, 18])

In [94]:
arr6

array([19, 18])

In [95]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 18],
       [10, 11, 17]])

In [107]:
arr7 = np.array([1, 3, 5, 8, 2, 7, 2, 4, 8])

In [108]:
arr7 < 5

array([ True,  True, False, False,  True, False,  True,  True, False], dtype=bool)

In [109]:
mask = arr7 < 5

In [110]:
mask

array([ True,  True, False, False,  True, False,  True,  True, False], dtype=bool)

In [111]:
arr7

array([1, 3, 5, 8, 2, 7, 2, 4, 8])

In [112]:
arr7[mask]

array([1, 3, 2, 2, 4])

In [113]:
arr7

array([1, 3, 5, 8, 2, 7, 2, 4, 8])

In [114]:
arr7[arr7 == 5]

array([5])

In [115]:
arr7 == 5

array([False, False,  True, False, False, False, False, False, False], dtype=bool)

In [120]:
arr7 < 3 & arr7 > 6

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [121]:
np.intersect1d(arr7 < 3, arr7 > 6)

array([False,  True], dtype=bool)

In [123]:
np.union1d(arr7 < 3, arr7 > 6)

array([False,  True], dtype=bool)

In [124]:
arr7 < 3

array([ True, False, False, False,  True, False,  True, False, False], dtype=bool)

In [125]:
arr7 > 6

array([False, False, False,  True, False,  True, False, False,  True], dtype=bool)

In [127]:
np.concatenate((arr7 < 3, arr7 > 6))

array([ True, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False,  True, False, False,  True], dtype=bool)

In [135]:
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 19],
       [10, 11, 22]])

In [142]:
arr4[0:, 0] < 3

array([ True, False, False, False], dtype=bool)

In [144]:
arr4[arr4[0:, 0] < 3, :]

array([[1, 2, 3]])