# Numpy
---

Numerical Processing library

> NumPy (pronounced "Numb Pie" or sometimes "Numb pee") is an extension to the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. - Wikipedia

In [1]:
import numpy as np

**Random Numbers**

*generate 9 random samples*

In [2]:
np.random.rand(9)

array([  6.51194548e-02,   2.62714309e-01,   6.96181807e-01,
         2.35599143e-01,   3.00688191e-04,   2.29823775e-01,
         7.33648544e-01,   2.01757114e-01,   4.58275352e-01])

In [3]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

*generate random integer between 1 and 99*

In [4]:
np.random.randint(1, 99)

42

In [5]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 'absolute_import',
 'bench',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings

**Array** or **Matrices**

*create a numpy array from list of integers*

In [6]:
arr = np.array([2, 5, 6, 9, 10])

In [7]:
arr

array([ 2,  5,  6,  9, 10])

*size of the matrix/array*

In [8]:
arr.size

5

*dimension of the matrix/array*

In [9]:
arr.ndim

1

*datatype of the matrix/array*

In [10]:
arr.dtype

dtype('int64')

> int64 is datatype of this array, ie each element in this array is 64 bit integer

*shape of the matrix/array*

In [11]:
arr.shape

(5,)

> shapes are evaluated as (row, column), one dimensional array can be looked as column matrix

**multi dimensional array**

In [12]:
arr2 = np.array([[1, 2, 3], [8, 9, 7]])

In [13]:
arr2

array([[1, 2, 3],
       [8, 9, 7]])

In [14]:
arr2.shape

(2, 3)

*size is total number of elements in an matrix*

In [15]:
arr2.size

6

In [16]:
arr2.ndim

2

**Scalar Operations in Matrix**

*lets work with our first array `arr`*

In [17]:
arr

array([ 2,  5,  6,  9, 10])

*multiplying array by 3*

In [18]:
arr * 3

array([ 6, 15, 18, 27, 30])

> multiplying scalar returns us new matrix where each element is multiplied by 3

*adding by 4*

In [19]:
arr + 4

array([ 6,  9, 10, 13, 14])

*adding two matrices/array*

In [20]:
arr + (arr + 2)

array([ 6, 12, 14, 20, 22])

> arr + 2 gives us new matrix after each element is added by two and we are adding this matrix to arr

*trying to add two matrices with different shapes*

In [21]:
arr + arr2

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

> Remember rules of matrix operations

*same can be done with multidimensional arrays*

In [22]:
arr2 * 3

array([[ 3,  6,  9],
       [24, 27, 21]])

**Creating array with other datatypes**

In [23]:
np.array([1.2, 4, 9, 5, 0])

array([ 1.2,  4. ,  9. ,  5. ,  0. ])

> All the integers are cast to float because one of the element is in float

In [24]:
np.array([1.2, 4, 9, 5, 0]).dtype

dtype('float64')

In [25]:
np.array(['1', 7, 9, 2.3])

array(['1', '7', '9', '2.3'], 
      dtype='<U3')

> same thing happens if one of the element is string

> Integer -> Float -> Unicode

In [26]:
np.array(['1', 7, 9, 2.3]) * 3

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U3') dtype('<U3') dtype('<U3')

> we cannot use scalar operations on string/unicode array

**Array based Operations**

In [27]:
arr2

array([[1, 2, 3],
       [8, 9, 7]])

In [28]:
help(arr2.all)

Help on built-in function all:

all(...) method of numpy.ndarray instance
    a.all(axis=None, out=None, keepdims=False)
    
    Returns True if all elements evaluate to True.
    
    Refer to `numpy.all` for full documentation.
    
    See Also
    --------
    numpy.all : equivalent function



*Boolean testing of elements*

In [29]:
arr2.all()

True

> Remember 0 evaluates to False and any other True

In [30]:
np.array([1, 0, 9]).all()

False

In [31]:
arr2

array([[1, 2, 3],
       [8, 9, 7]])

In [32]:
arr3 = np.array([[1, 0, 9], [2, 6, 7]])

In [33]:
arr3.all()

False

In [34]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

*axis `0` is means operate column wise/ or vertically*

In [35]:
arr3.all(axis=0)

array([ True, False,  True], dtype=bool)

*axis `1` means operate row wise/ or horizontally*

In [36]:
arr3.all(axis=1)

array([False,  True], dtype=bool)

> Both returns a new boolean array

**Cumulative Sum**

In [37]:
help(arr3.cumsum)

Help on built-in function cumsum:

cumsum(...) method of numpy.ndarray instance
    a.cumsum(axis=None, dtype=None, out=None)
    
    Return the cumulative sum of the elements along the given axis.
    
    Refer to `numpy.cumsum` for full documentation.
    
    See Also
    --------
    numpy.cumsum : equivalent function



In [38]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [39]:
arr3.cumsum()

array([ 1,  1, 10, 12, 18, 25])

In [40]:
arr3.cumsum(axis=0)

array([[ 1,  0,  9],
       [ 3,  6, 16]])

In [41]:
arr3.cumsum(axis=1)

array([[ 1,  1, 10],
       [ 2,  8, 15]])

In [42]:
help(arr3.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



**Mean**

In [43]:
arr3.mean()

4.166666666666667

In [44]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

**Minimum**

In [45]:
arr3.min()

0

**Maximum**

In [46]:
arr3.max()

9

**Median**

In [47]:
np.median(arr3)

4.0

**Standard Deviation**

In [48]:
arr3.std()

3.337497399083464

**Matrix Manipulation**

In [49]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [50]:
help(arr3.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function



In [51]:
arr3.shape

(2, 3)

In [52]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [53]:
arr3.reshape((6,))

array([1, 0, 9, 2, 6, 7])

> (6, ) is single valued tuple, elements are reorganized in order to adjust new shape

> Returns a new matrix/array, doesnot change the old

In [54]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [55]:
arr3.reshape((3, 2))

array([[1, 0],
       [9, 2],
       [6, 7]])

In [56]:
help(arr3.transpose)

Help on built-in function transpose:

transpose(...) method of numpy.ndarray instance
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    For a 1-D array, this has no effect. (To change between column and
    row vectors, first cast the 1-D array into a matrix object.)
    For a 2-D array, this is the usual matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided and
    ``a.shape = (i[0], i[1], ... i[n-2], i[n-1])``, then
    ``a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0])``.
    
    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints
    
     * None or no argument: reverses the order of the axes.
    
     * tuple of ints: `i` in the `j`-th place in the tuple means `a`'s
       `i`-th axis becomes `a.transpose()`'s `j`-th axis.
    
     * `n` ints: same as an n-tuple of the same ints (this form is
       intended simply as

In [57]:
arr3

array([[1, 0, 9],
       [2, 6, 7]])

In [58]:
arr3.transpose()

array([[1, 2],
       [0, 6],
       [9, 7]])

*show bytes of memory used*

In [59]:
arr3.nbytes

48

*performance test between list and numpy array*

In [60]:
lst = [x for x in range(0, 99)]

In [61]:
%timeit [x*3 for x in lst]

100000 loops, best of 3: 5.24 µs per loop


In [62]:
arr_lst = np.array(lst)

In [63]:
%timeit arr_lst * 3

The slowest run took 26.62 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.18 µs per loop
