In [2]:
import numpy as np

In [8]:
np.inf > 1000000000.0

True

In [27]:
np.tile(np.array([[1, 2], [1, 2]]), (2, 2, 2))

array([[[1, 2, 1, 2],
        [1, 2, 1, 2],
        [1, 2, 1, 2],
        [1, 2, 1, 2]],

       [[1, 2, 1, 2],
        [1, 2, 1, 2],
        [1, 2, 1, 2],
        [1, 2, 1, 2]]])

In [19]:
np.tile?

In [31]:
np.dtype(np.int32)

dtype('int32')

In [32]:
np.dtype([('r', np.ubyte)])

dtype([('r', 'u1')])

In [33]:
np.random.uniform(-10,+10,10)

array([-9.30869973,  6.63005676, -6.44652679, -3.04991617, -7.12192213,
        9.66614986,  3.91887023,  0.90748119,  9.08328894,  4.25914548])

In [34]:
np.linspace(-10, +10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [36]:
np.trunc(1.234567)

1.0

In [37]:
np.trunc(1.87654)

1.0

In [38]:
np.trunc?

In [39]:
_ = 1
print(_)

1
