# Numpy
---

Numerical Processing library

> NumPy (pronounced "Numb Pie" or sometimes "Numb pee") is an extension to the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. - Wikipedia

In [74]:
import numpy as np

In [75]:
np.__version__

'1.11.1'

## Arrays

*Create a new array*

In [76]:
a = np.array([1, 2, 3])

In [77]:
a

array([1, 2, 3])

*Array are generally can be considered as Matrices*

$$
\begin{bmatrix}
    1 & 2 & 3
\end{bmatrix}
$$

**Multidimensional array**

In [78]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

*can be more visually seen as*

$$
\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6
\end{bmatrix}
$$

In [79]:
b = np.array([4, 5, 6])

In [80]:
b

array([4, 5, 6])

## Array Operations

*Adding two matrices*

In [81]:
a + b

array([5, 7, 9])

> *Result: * $[1+4, 2+5, 3+6]$

*Adding a scalar to matrix*

In [82]:
a + 1

array([2, 3, 4])

*Dividing*

In [83]:
b / a

array([ 4. ,  2.5,  2. ])

In [84]:
b // a

array([4, 2, 2])

> *Result: * $[4\div1, 5\div2, 6\div3]$

*Dividing by a scalar*

In [85]:
b / 2

array([ 2. ,  2.5,  3. ])

In [86]:
b // 2

array([2, 2, 3])

> Division is default python behavior

*Multiplying by scalar*

In [87]:
b * 3

array([12, 15, 18])

*Multiplying two array*

In [88]:
a * b

array([ 4, 10, 18])

> *Result is * $[1*4, 2*5, 3*6]$

> *Remember operations between arrays is element wise, It is not the matrix multiplication ( vector product )*


*Dot Product*

In [89]:
a.dot(b)

32

### Array attributes

In [90]:
type(a)

numpy.ndarray

*datatype of a array*

In [91]:
a.dtype

dtype('int64')

> This means that all the elements are of type int64.

*Note: Numpy array elements are of single types unlike of multitype of list*

*Size: total number of items in array*

In [92]:
a.size

3

In [93]:
c.size

6

*len is different than size*

In [94]:
len(c)

2

> `c` is multidimensional array with 2 rows and 3 columns, `len` gave length of rows

*Shape: shape of array*

In [95]:
a.shape

(3,)

> *length of a along first dimension, which is only `a` has*

In [96]:
c.shape

(2, 3)

> *shape always returns a tuple*

> *shape of array is length of array, in each dimension*



In [97]:
np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]).shape

(3, 3)

*shape of a three dimensional array*

In [98]:
np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]).shape

(2, 2, 3)

*Dimension of array*

In [99]:
a.ndim

1

In [100]:
b.ndim

1

In [101]:
c.ndim

2

**Array with floating types or unicode types**

In [102]:
d = np.array([1.0, 2, 4, 9])
d

array([ 1.,  2.,  4.,  9.])

> *All the other integer items are converted to float*

In [103]:
d.dtype

dtype('float64')

In [104]:
e = np.array(['a', 'b', 'c', 'd'])
e

array(['a', 'b', 'c', 'd'], 
      dtype='<U1')

In [105]:
e.dtype

dtype('<U1')

*Size of array items in bytes*

In [106]:
# int64
a.itemsize

8

In [107]:
# float64
d.itemsize

8

In [108]:
# <U1
e.itemsize

4

*Memory usage of array*

In [109]:
e.nbytes

16

*Which is same as*

In [110]:
e.itemsize * e.size

16

In [111]:
a.nbytes

24

### Array Indexing

In [112]:
a

array([1, 2, 3])

*Working with array index is "similar" to list index*

In [113]:
# select first element
a[0]

1

In [114]:
# select last element
a[-1]

3

In [115]:
# assign a new value to particular index
a[1] = 7

In [116]:
a

array([1, 7, 3])

*fill into array*

In [117]:
b.fill(0)

In [118]:
b

array([0, 0, 0])

**Type cohersion**

In [119]:
a[0] = 2.3

In [120]:
a

array([2, 7, 3])

> *Since, a is of dtype int64. 2.3 is cast to int above*

In [121]:
b.fill(1.1)

In [122]:
b

array([1, 1, 1])

> *Same goes for fill*

### Array slicing

**array[lower:upper:step]**

- `lower` if ommitted defaults to 0
- `upper` if ommitted defaults to length of array
- `step`  if ommitted defaults to 1 

In [123]:
a

array([2, 7, 3])

In [124]:
a[:]

array([2, 7, 3])

In [125]:
a[0:]

array([2, 7, 3])

In [126]:
a[:-1]

array([2, 7])

In [127]:
a[:2]

array([2, 7])

In [128]:
a[1:]

array([7, 3])

In [129]:
a[::2]

array([2, 3])

In [130]:
a[::-1]

array([3, 7, 2])

In [131]:
a[-2:]

array([7, 3])

**Cool tricks with array slicing**

*finding out mid point of every consecutive items in an array*

In [132]:
aa = np.array([1, 2, 3, 5, 8, 13, 21, 34])

In [133]:
aa[1:]

array([ 2,  3,  5,  8, 13, 21, 34])

In [134]:
aa[:-1]

array([ 1,  2,  3,  5,  8, 13, 21])

In [135]:
aa[1:] + aa[:-1]

array([ 3,  5,  8, 13, 21, 34, 55])

In [136]:
(aa[1:] + aa[:-1]) / 2

array([  1.5,   2.5,   4. ,   6.5,  10.5,  17. ,  27.5])

### Creating arrays

*create an empty array*

In [137]:
np.empty(3)

array([  1.48219694e-323,   3.45845952e-323,   9.88131292e-324])

*array of zeros*

In [138]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [139]:
np.zeros((3,))

array([ 0.,  0.,  0.])

In [140]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

*array of ones*

In [141]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

*from range*

In [142]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])


*Random Numbers*

In [143]:
np.random.rand(3)

array([ 0.82860062,  0.35108145,  0.23552213])