# Numpy
---

Numerical Processing library

> NumPy (pronounced "Numb Pie" or sometimes "Numb pee") is an extension to the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays. - Wikipedia

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.1'

## Array Operations

*Create a new array*

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

*Array are generally can be considered as Matrices*

$$
\begin{bmatrix}
    1 & 2 & 3
\end{bmatrix}
$$

**Multidimensional array**

In [24]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

*can be more visually seen as*

$$
\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6
\end{bmatrix}
$$

In [6]:
b = np.array([4, 5, 6])

In [7]:
b

array([4, 5, 6])

*Adding two matrices*

In [9]:
a + b

array([5, 7, 9])

> *Result: * $[1+4, 2+5, 3+6]$

*Adding a scalar to matrix*

In [11]:
a + 1

array([2, 3, 4])

*Dividing*

In [10]:
b / a

array([ 4. ,  2.5,  2. ])

In [13]:
b // a

array([4, 2, 2])

> *Result: * $[4\div1, 5\div2, 6\div3]$

*Dividing by a scalar*

In [12]:
b / 2

array([ 2. ,  2.5,  3. ])

In [14]:
b // 2

array([2, 2, 3])

> Division is default python behavior

*Multiplying by scalar*

In [15]:
b * 3

array([12, 15, 18])

*Multiplying two array*

In [19]:
a * b

array([ 4, 10, 18])

> *Result is * $[1*4, 2*5, 3*6]$

> *Remember operations between arrays is element wise, It is not the matrix multiplication ( vector product )*


*Dot Product*

In [8]:
a.dot(b)

32

**Numpy array types and attributes**

In [20]:
type(a)

numpy.ndarray

*datatype of a array*

In [21]:
a.dtype

dtype('int64')

> This means that all the elements are of type int64.

*Note: Numpy array elements are of single types unlike of multitype of list*

*Size: total number of items in array*

In [22]:
a.size

3

In [25]:
c.size

6

*len is different than size*

In [26]:
len(c)

2

> `c` is multidimensional array with 2 rows and 3 columns, `len` gave length of rows

*Shape: shape of array*

In [28]:
a.shape

(3,)

> *length of a along first dimension, which is only `a` has*

In [29]:
c.shape

(2, 3)

> *shape always returns a tuple*

> *shape of array is length of array, in each dimension*



In [44]:
np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]).shape

(3, 3)

*shape of a three dimensional array*

In [47]:
np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]).shape

(2, 2, 3)

*Dimension of array*

In [30]:
a.ndim

1

In [31]:
b.ndim

1

In [32]:
c.ndim

2

**Array with floating types or unicode types**

In [34]:
d = np.array([1.0, 2, 4, 9])
d

array([ 1.,  2.,  4.,  9.])

> *All the other integer items are converted to float*

In [35]:
d.dtype

dtype('float64')

In [36]:
e = np.array(['a', 'b', 'c', 'd'])
e

array(['a', 'b', 'c', 'd'], 
      dtype='<U1')

In [37]:
e.dtype

dtype('<U1')

*Size of array items in bytes*

In [38]:
# int64
a.itemsize

8

In [39]:
# float64
d.itemsize

8

In [40]:
# <U1
e.itemsize

4

*Memory usage of array*

In [48]:
e.nbytes

16

*Which is same as*

In [50]:
e.itemsize * e.size

16

In [49]:
a.nbytes

24

**Random Numbers**

*generate 9 random samples*

In [ ]:
np.random.rand(9)

In [ ]:
help(np.random.rand)

*generate random integer between 1 and 99*

In [ ]:
np.random.randint(1, 99)

In [ ]:
dir(np.random)

In [ ]:
help(arr2.all)

*Boolean testing of elements*

In [ ]:
arr2.all()

> Remember 0 evaluates to False and any other True

In [ ]:
np.array([1, 0, 9]).all()

In [ ]:
arr2

In [ ]:
arr3 = np.array([[1, 0, 9], [2, 6, 7]])

In [ ]:
arr3.all()

In [ ]:
arr3

*axis `0` is means operate column wise/ or vertically*

In [ ]:
arr3.all(axis=0)

*axis `1` means operate row wise/ or horizontally*

In [ ]:
arr3.all(axis=1)

> Both returns a new boolean array

**Cumulative Sum**

In [ ]:
help(arr3.cumsum)

In [ ]:
arr3

In [ ]:
arr3.cumsum()

In [ ]:
arr3.cumsum(axis=0)

In [ ]:
arr3.cumsum(axis=1)

In [ ]:
help(arr3.mean)

**Mean**

In [ ]:
arr3.mean()

In [ ]:
arr3

**Minimum**

In [ ]:
arr3.min()

**Maximum**

In [ ]:
arr3.max()

**Median**

In [ ]:
np.median(arr3)

**Standard Deviation**

In [ ]:
arr3.std()

**Matrix Manipulation**

In [ ]:
arr3

In [ ]:
help(arr3.reshape)

In [ ]:
arr3.shape

In [ ]:
arr3

In [ ]:
arr3.reshape((6,))

> (6, ) is single valued tuple, elements are reorganized in order to adjust new shape

> Returns a new matrix/array, doesnot change the old

In [ ]:
arr3

In [ ]:
arr3.reshape((3, 2))

In [ ]:
help(arr3.transpose)

In [ ]:
arr3

In [ ]:
arr3.transpose()

*show bytes of memory used*

In [ ]:
arr3.nbytes