[https://wiki.python.org/moin/BitwiseOperators](https://wiki.python.org/moin/BitwiseOperators)

In [1]:
import numpy as np

In [2]:
np.array([1, 3, 4, 6])

array([1, 3, 4, 6])

In [3]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [4]:
np.array([1.5, 1, 8])

array([ 1.5,  1. ,  8. ])

In [5]:
np.array([1.5 , 'a'])

array(['1.5', 'a'], 
      dtype='<U32')

In [10]:
arr = np.linspace(0, 99, num=20)

In [11]:
arr

array([  0.        ,   5.21052632,  10.42105263,  15.63157895,
        20.84210526,  26.05263158,  31.26315789,  36.47368421,
        41.68421053,  46.89473684,  52.10526316,  57.31578947,
        62.52631579,  67.73684211,  72.94736842,  78.15789474,
        83.36842105,  88.57894737,  93.78947368,  99.        ])

In [12]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__r

In [13]:
arr.dtype

dtype('float64')

In [14]:
arr.shape

(20,)

In [15]:
arr.size

20

In [16]:
arr

array([  0.        ,   5.21052632,  10.42105263,  15.63157895,
        20.84210526,  26.05263158,  31.26315789,  36.47368421,
        41.68421053,  46.89473684,  52.10526316,  57.31578947,
        62.52631579,  67.73684211,  72.94736842,  78.15789474,
        83.36842105,  88.57894737,  93.78947368,  99.        ])

In [17]:
arr * 2

array([   0.        ,   10.42105263,   20.84210526,   31.26315789,
         41.68421053,   52.10526316,   62.52631579,   72.94736842,
         83.36842105,   93.78947368,  104.21052632,  114.63157895,
        125.05263158,  135.47368421,  145.89473684,  156.31578947,
        166.73684211,  177.15789474,  187.57894737,  198.        ])

In [18]:
arr + 4

array([   4.        ,    9.21052632,   14.42105263,   19.63157895,
         24.84210526,   30.05263158,   35.26315789,   40.47368421,
         45.68421053,   50.89473684,   56.10526316,   61.31578947,
         66.52631579,   71.73684211,   76.94736842,   82.15789474,
         87.36842105,   92.57894737,   97.78947368,  103.        ])

In [19]:
np.array([1, 2, 5]) + np.array([3, 4, 6, 7])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [20]:
arr / 3

array([  0.        ,   1.73684211,   3.47368421,   5.21052632,
         6.94736842,   8.68421053,  10.42105263,  12.15789474,
        13.89473684,  15.63157895,  17.36842105,  19.10526316,
        20.84210526,  22.57894737,  24.31578947,  26.05263158,
        27.78947368,  29.52631579,  31.26315789,  33.        ])

In [21]:
arr % 3

array([ 0.        ,  2.21052632,  1.42105263,  0.63157895,  2.84210526,
        2.05263158,  1.26315789,  0.47368421,  2.68421053,  1.89473684,
        1.10526316,  0.31578947,  2.52631579,  1.73684211,  0.94736842,
        0.15789474,  2.36842105,  1.57894737,  0.78947368,  0.        ])

In [23]:
arr % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False], dtype=bool)

In [24]:
arr > 55

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [25]:
arr[arr > 55]

array([ 57.31578947,  62.52631579,  67.73684211,  72.94736842,
        78.15789474,  83.36842105,  88.57894737,  93.78947368,  99.        ])

In [27]:
arr[10]

52.105263157894733

In [29]:
arr_mask = arr > 55
[item for idx, item in enumerate(arr) if arr_mask[idx]]

[57.315789473684205,
 62.526315789473685,
 67.73684210526315,
 72.94736842105263,
 78.157894736842096,
 83.368421052631575,
 88.578947368421055,
 93.78947368421052,
 99.0]

In [30]:
arr

array([  0.        ,   5.21052632,  10.42105263,  15.63157895,
        20.84210526,  26.05263158,  31.26315789,  36.47368421,
        41.68421053,  46.89473684,  52.10526316,  57.31578947,
        62.52631579,  67.73684211,  72.94736842,  78.15789474,
        83.36842105,  88.57894737,  93.78947368,  99.        ])

In [35]:
arr[(arr < 25) & (arr > 75)]

array([], dtype=float64)

In [36]:
and

SyntaxError: invalid syntax (<ipython-input-36-3e9ddeb7e698>, line 1)

In [38]:
arr < 25 & arr > 75

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [40]:
arr[[arr < 25] and [arr > 75]]

array([ 78.15789474,  83.36842105,  88.57894737,  93.78947368,  99.        ])

In [41]:
[arr < 25]

[array([ True,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False], dtype=bool)]

In [42]:
[arr > 75]

[array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True,  True,
         True,  True], dtype=bool)]

In [43]:
[arr < 25] and [arr > 75]

[array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True,  True,
         True,  True], dtype=bool)]

In [44]:
4 and 5

5

In [45]:
4 or 5

4

In [47]:
arr[(arr < 25) | (arr > 75)]

array([  0.        ,   5.21052632,  10.42105263,  15.63157895,
        20.84210526,  78.15789474,  83.36842105,  88.57894737,
        93.78947368,  99.        ])

In [48]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [49]:
np.zeros((2, 3, 4))

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [50]:
np.zeros((2, 2, 3, 4))

array([[[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]])

In [51]:
np.arange(55)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54])

In [57]:
np.arange(55).reshape(4, 5)

ValueError: total size of new array must be unchanged

In [56]:
np.arange(55).reshape(11, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [58]:
np.arange(40).reshape(2, 4, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [59]:
arr

array([  0.        ,   5.21052632,  10.42105263,  15.63157895,
        20.84210526,  26.05263158,  31.26315789,  36.47368421,
        41.68421053,  46.89473684,  52.10526316,  57.31578947,
        62.52631579,  67.73684211,  72.94736842,  78.15789474,
        83.36842105,  88.57894737,  93.78947368,  99.        ])

In [60]:
arr[10]

52.105263157894733

In [61]:
arr[10:15]

array([ 52.10526316,  57.31578947,  62.52631579,  67.73684211,  72.94736842])

In [62]:
arr2 = np.arange(55).reshape(11, 5)

In [63]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [64]:
arr2[10]

array([50, 51, 52, 53, 54])

In [66]:
arr2[5][3]

28

In [69]:
arr2[:][3]

array([15, 16, 17, 18, 19])

In [71]:
arr2[:,3]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53])

In [72]:
arr2[3]

array([15, 16, 17, 18, 19])

In [74]:
arr2[3, 3]

18