# Session 2
---

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(0, 16)

In [5]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
arr1[2:7]

array([2, 3, 4, 5, 6])

In [8]:
arr1[2:9:2]

array([2, 4, 6, 8])

In [9]:
abc = arr1[5:9]
abc

array([5, 6, 7, 8])

In [10]:
abc = 7

In [11]:
abc

7

In [12]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
abc = arr1[5:9]
abc

array([5, 6, 7, 8])

In [14]:
abc

array([5, 6, 7, 8])

In [15]:
abc[:] = 7

In [16]:
abc

array([7, 7, 7, 7])

In [17]:
arr1

array([ 0,  1,  2,  3,  4,  7,  7,  7,  7,  9, 10, 11, 12, 13, 14, 15])

In [19]:
arr1[3:6]

array([3, 4, 7])

In [20]:
arr1[3:6] * 3

array([ 9, 12, 21])

In [21]:
arr1[9:12] // 5

array([1, 2, 2])

In [22]:
arr1

array([ 0,  1,  2,  3,  4,  7,  7,  7,  7,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.array([1, 3, 5]) + np.array([4, 5, 6])

array([ 5,  8, 11])

In [24]:
np.array([1, 3, 5]) - np.array([4, 5, 6])

array([-3, -2, -1])

In [25]:
np.array([1, 3, 5]) * np.array([4, 5, 6])

array([ 4, 15, 30])

In [26]:
np.array([[1, 3], [2, 4]]) * np.array([4, 5])

array([[ 4, 15],
       [ 8, 20]])

In [27]:
np.array([[1, 3], [2, 4]]) * np.array([4, 5, 6])

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [28]:
np.array([[1, 3], [2, 4]]) * np.array([[4, 5], [1, 2]])

array([[ 4, 15],
       [ 2,  8]])

In [30]:
np.multiply([[1, 3], [2, 4]], np.array([[4, 5], [1, 2]]))

array([[ 4, 15],
       [ 2,  8]])

In [31]:
np.array([[1, 3], [2, 4]]) @ np.array([[4, 5], [1, 2]])

array([[ 7, 11],
       [12, 18]])

In [32]:
np.matmul([[1, 3], [2, 4]], np.array([[4, 5], [1, 2]]))

array([[ 7, 11],
       [12, 18]])

In [34]:
np.dot([[1, 3], [2, 4]], np.array([[4, 5], [1, 2]]))

array([[ 7, 11],
       [12, 18]])

In [35]:
np.cross([[1, 3], [2, 4]], np.array([[4, 5], [1, 2]]))

array([-7,  0])

In [36]:
np.cross([1, 2, 3], np.array([3, 4, 5]))

array([-2,  4, -2])

### multidimensional slices

In [37]:
arr2 = np.arange(0, 12).reshape((3, 4))

In [38]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
arr2[1]

array([4, 5, 6, 7])

In [40]:
arr2[1][1]

5

In [41]:
arr2[1, 1]

5

In [43]:
arr2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
arr2[0:2][0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
arr2[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [47]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
arr2[::2, 1:3]

array([[ 1,  2],
       [ 9, 10]])

In [49]:
arr2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [50]:
arr2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [51]:
arr2[[0, 1]]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

**Try this:**

In [52]:
arr3 = np.arange(0, 24).reshape((2, 3, 4))

In [53]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
arr3[:, 0, ::2]

array([[ 0,  2],
       [12, 14]])

In [55]:
arr3[:, [0, 1]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [56]:
arr3[:, [0, 1], [1, 3]]

array([[ 1,  7],
       [13, 19]])

In [57]:
arr3[:, :2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [58]:
arr3[:, :2, [1, 3]]

array([[[ 1,  3],
        [ 5,  7]],

       [[13, 15],
        [17, 19]]])

#### masking and boolean array

In [ ]:
mask = np.array([True, False, True, True])

In [ ]:
mask

In [ ]:
arr11 = np.array([5, 6, 8, 3])

In [ ]:
arr11[mask]

In [ ]:
arr12 = np.arange(1, 15)

In [ ]:
arr12

In [ ]:
arr12 / 3 < 2

In [ ]:
arr12[arr12 / 3 < 2]

In [ ]:
arr12 % 3 == 0

In [ ]:
 arr12 % 5 == 0

In [ ]:
(arr12 % 3 == 0) or (arr12 % 5 == 0)

In [ ]:
(arr12 % 3 == 0) | (arr12 % 5 == 0)

In [ ]:
(arr12 % 3 == 0) & (arr12 % 5 == 0)

In [ ]:
arr12[(arr12 % 3 == 0) | (arr12 % 5 == 0)]

In [ ]:
arr12 % 3 == 0 | arr12 % 5 == 0

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
from scipy import misc

In [ ]:
face = misc.face()

In [ ]:
%matplotlib inline

In [ ]:
plt.imshow(face)

In [ ]:
face

In [ ]:
face.shape

In [ ]:
plt.imshow(misc.ascent())

In [ ]:
ascent = misc.ascent()

In [ ]:
ascent

In [ ]:
ascent.shape

In [ ]:
ascent.size

In [ ]:
ascent.ndim

In [ ]:
face.ndim

In [ ]:
face.shape

In [ ]:
asc2 = ascent//89

In [ ]:
plt.imshow(asc2)

In [ ]:
asc2

In [ ]:
plt.imshow(asc2[0:6, 0:6])

In [ ]:
plt.imshow(ascent[0:100, 0:100])

In [ ]:
ascent < 80

In [ ]:
ascent[ascent < 80]

In [ ]:
ascent[(ascent < 80) | (ascent > 100)]

In [ ]:
2 < 7 and 3 > 9 

In [ ]:
(ascent < 80) | (ascent > 100)

In [ ]:
asc3 = ascent[(ascent < 80) | (ascent > 100)]

In [ ]:
ascent

In [ ]:
asc3.shape

In [ ]:
asc3.size

In [ ]:
asc5 = ascent[:, 0:8]

In [ ]:
asc5

In [ ]:
asc5[0, 0] = 221

In [ ]:
asc5

In [ ]:
ascent[ascent < 100]

In [ ]:
ascent[ascent < 100] * 2

In [ ]:
ascent

**H/W** continue

In [ ]:
face

In [ ]:
plt.imshow(face)

In [ ]:
plt.imshow(face[50:500, 400:900])

In [ ]:
plt.imshow(face[50:500, 400:900, 1])

In [ ]:
plt.imshow(face[50:500, 400:900, 1:])

In [ ]:
face[50:500, 400:900, 1:]

In [ ]:
face[50:500, 400:900, 1]

In [ ]:
p_image = face[400:600, 600:800]

In [ ]:
p_image

In [ ]:
p_image > 200

In [ ]:
p_image[p_image > 200] = 255

In [ ]:
plt.imshow(p_image)

In [ ]:
p_image[(p_image > 200) | (p_image < 50)] = 255

In [ ]:
plt.imshow(p_image)