# Numpy Practice Session
---

In [1]:
import numpy as np

In [2]:
ar = np.array([1, 2, 0, 0, 4, 0])

In [3]:
np.info(np.nonzero)

 nonzero(a)

Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order. The corresponding non-zero
values can be obtained with::

    a[nonzero(a)]

To group the indices by element, rather than dimension, use::

    transpose(nonzero(a))

The result of this is always a 2-D array, with a row for
each non-zero element.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the input array.

Examples
--------
>>> x = np.array([[1,0,0], [0,2,0], [1,1,0]])
>>> x
array([[1, 0, 0],
       

In [4]:
np.nonzero(ar)

(array([0, 1, 4]),)

In [5]:
help(np.indices)

Help on function indices in module numpy.core.numeric:

indices(dimensions, dtype=<class 'int'>)
    Return an array representing the indices of a grid.
    
    Compute an array where the subarrays contain index values 0,1,...
    varying only along the corresponding axis.
    
    Parameters
    ----------
    dimensions : sequence of ints
        The shape of the grid.
    dtype : dtype, optional
        Data type of the result.
    
    Returns
    -------
    grid : ndarray
        The array of grid indices,
        ``grid.shape = (len(dimensions),) + tuple(dimensions)``.
    
    See Also
    --------
    mgrid, meshgrid
    
    Notes
    -----
    The output shape is obtained by prepending the number of dimensions
    in front of the tuple of dimensions, i.e. if `dimensions` is a tuple
    ``(r0, ..., rN-1)`` of length ``N``, the output shape is
    ``(N,r0,...,rN-1)``.
    
    The subarrays ``grid[k]`` contains the N-D array of indices along the
    ``k-th`` axis. Explicitly:

In [6]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [7]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
np.random.rand(3, 3, 3)

array([[[ 0.63494472,  0.59759257,  0.9086835 ],
        [ 0.89052749,  0.4082488 ,  0.20807253],
        [ 0.76146862,  0.40444054,  0.24692421]],

       [[ 0.31053565,  0.21599319,  0.22275212],
        [ 0.72281008,  0.09853107,  0.78129954],
        [ 0.5253175 ,  0.16293704,  0.34955548]],

       [[ 0.63374141,  0.02765575,  0.00858584],
        [ 0.49899288,  0.79450633,  0.77449634],
        [ 0.21890743,  0.97930032,  0.64168985]]])

In [16]:
ar = np.arange(3, 15).reshape((3, 4))

In [17]:
ar

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [19]:
ar[1:-1, 1:-1]

array([[8, 9]])

In [20]:
ar[1:-1, 1:-1] = 0

In [21]:
ar

array([[ 3,  4,  5,  6],
       [ 7,  0,  0, 10],
       [11, 12, 13, 14]])

In [22]:
ar[[0, -1]]

array([[ 3,  4,  5,  6],
       [11, 12, 13, 14]])

In [23]:
ar[[0, -1], [0, -1]]

array([ 3, 14])

In [25]:
ar[[0, -1]] = 1

In [26]:
ar

array([[ 1,  1,  1,  1],
       [ 7,  0,  0, 10],
       [ 1,  1,  1,  1]])

In [28]:
ar[:, [0, -1]]

array([[ 1,  1],
       [ 7, 10],
       [ 1,  1]])

In [29]:
ar[:, [0, -1]] = 1

In [30]:
ar

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [31]:
np.info(np.pad)

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

In [32]:
ar = np.arange(1, 13).reshape((3, 4))

In [33]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
np.pad(ar, 1, mode='constant')

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [38]:
np.pad(ar, 1, mode='constant', constant_values=5)

array([[ 5,  5,  5,  5,  5,  5],
       [ 5,  1,  2,  3,  4,  5],
       [ 5,  5,  6,  7,  8,  5],
       [ 5,  9, 10, 11, 12,  5],
       [ 5,  5,  5,  5,  5,  5]])

In [42]:
np.pad(ar, 1, mode='edge')

array([[ 1,  1,  2,  3,  4,  4],
       [ 1,  1,  2,  3,  4,  4],
       [ 5,  5,  6,  7,  8,  8],
       [ 9,  9, 10, 11, 12, 12],
       [ 9,  9, 10, 11, 12, 12]])

In [43]:
np.pad(ar, 1, mode='maximum')

array([[12,  9, 10, 11, 12, 12],
       [ 4,  1,  2,  3,  4,  4],
       [ 8,  5,  6,  7,  8,  8],
       [12,  9, 10, 11, 12, 12],
       [12,  9, 10, 11, 12, 12]])

In [44]:
0 * np.nan

nan

In [45]:
np.nan == np.nan

False

In [46]:
np.nan is np.nan

True

In [47]:
np.inf > np.nan

False

In [48]:
np.nan - np.nan

nan

In [49]:
0.3 == 3 * 0.1

False

In [50]:
3 * 0.1

0.30000000000000004

In [51]:
np.nan is np.int64

False

In [52]:
np.nan is np.float64

False

In [57]:
6 * 7 * 8

336

In [58]:
ar3 = np.arange(3, 339).reshape((6, 7, 8))

In [59]:
ar3

array([[[  3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18],
        [ 19,  20,  21,  22,  23,  24,  25,  26],
        [ 27,  28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41,  42],
        [ 43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58]],

       [[ 59,  60,  61,  62,  63,  64,  65,  66],
        [ 67,  68,  69,  70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79,  80,  81,  82],
        [ 83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105, 106],
        [107, 108, 109, 110, 111, 112, 113, 114]],

       [[115, 116, 117, 118, 119, 120, 121, 122],
        [123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138],
        [139, 140, 141, 142, 143, 144, 145, 146],
        [147, 148, 149, 150, 151, 152, 153, 154],
        [155, 156, 157, 158, 159, 160, 161, 16

In [61]:
ar3[100]

IndexError: index 100 is out of bounds for axis 0 with size 6

In [62]:
np.unravel_index

<function numpy.core.multiarray.unravel_index>

In [63]:
np.info(np.indices)

 indices(dimensions, dtype=<class 'int'>)

Return an array representing the indices of a grid.

Compute an array where the subarrays contain index values 0,1,...
varying only along the corresponding axis.

Parameters
----------
dimensions : sequence of ints
    The shape of the grid.
dtype : dtype, optional
    Data type of the result.

Returns
-------
grid : ndarray
    The array of grid indices,
    ``grid.shape = (len(dimensions),) + tuple(dimensions)``.

See Also
--------
mgrid, meshgrid

Notes
-----
The output shape is obtained by prepending the number of dimensions
in front of the tuple of dimensions, i.e. if `dimensions` is a tuple
``(r0, ..., rN-1)`` of length ``N``, the output shape is
``(N,r0,...,rN-1)``.

The subarrays ``grid[k]`` contains the N-D array of indices along the
``k-th`` axis. Explicitly::

    grid[k,i0,i1,...,iN-1] = ik

Examples
--------
>>> grid = np.indices((2, 3))
>>> grid.shape
(2, 2, 3)
>>> grid[0]        # row indices
array([[0, 0, 0],
       [1, 1, 1]])

In [67]:
ar3.flatten()[100]

103

In [70]:
ar3[1][5][4]

103

In [71]:
np.info(np.unravel_index)

unravel_index(indices, dims, order='C')

Converts a flat index or array of flat indices into a tuple
of coordinate arrays.

Parameters
----------
indices : array_like
    An integer array whose elements are indices into the flattened
    version of an array of dimensions ``dims``. Before version 1.6.0,
    this function accepted just one index value.
dims : tuple of ints
    The shape of the array to use for unraveling ``indices``.
order : {'C', 'F'}, optional
    Determines whether the indices should be viewed as indexing in
    row-major (C-style) or column-major (Fortran-style) order.

    .. versionadded:: 1.6.0

Returns
-------
unraveled_coords : tuple of ndarray
    Each array in the tuple has the same shape as the ``indices``
    array.

See Also
--------
ravel_multi_index

Examples
--------
>>> np.unravel_index([22, 41, 37], (7,6))
(array([3, 6, 6]), array([4, 5, 1]))
>>> np.unravel_index([31, 41, 13], (7,6), order='F')
(array([3, 6, 6]), array([4, 5, 1]))

>>> np.unravel_index

In [72]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [73]:
ar1 = np.random.rand(5, 3)

In [74]:
ar2 = np.random.rand(3, 2)

In [75]:
ar1

array([[ 0.40987926,  0.81099435,  0.22660489],
       [ 0.99608653,  0.44075755,  0.12373964],
       [ 0.88175944,  0.63746225,  0.46951875],
       [ 0.78423246,  0.4571699 ,  0.95361953],
       [ 0.88772216,  0.90582889,  0.87055169]])

In [76]:
ar2

array([[ 0.89997515,  0.63554457],
       [ 0.94660135,  0.91691775],
       [ 0.34050948,  0.11828664]])

In [77]:
np.info(np.dot)

dot(a, b, out=None)

Dot product of two arrays.

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
arrays to inner product of vectors (without complex conjugation). For
N dimensions it is a sum product over the last axis of `a` and
the second-to-last of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the right type, must be
    C-contiguous, and its dtype must be the dtype that would be returned
    for `dot(a,b)`. This is a performance feature. Therefore, if these
    conditions are not met, an exception is raised, instead of attempting
    to be flexible.

Returns
-------
output : ndarray
    Returns the dot product of `a` and `b`.  If `a` and `b` are both
    scalars or both 1-D arrays then a scalar is returned; ot

In [78]:
np.dot(ar1, ar2)

array([[ 1.2137306 ,  1.03091598],
       [ 1.35580934,  1.05183255],
       [ 1.5568598 ,  1.20043567],
       [ 1.46326386,  1.03040233],
       [ 1.95281784,  1.49773222]])

In [79]:
np.dot(ar2, ar1)

ValueError: shapes (3,2) and (5,3) not aligned: 2 (dim 1) != 5 (dim 0)

In [81]:
ar1 @ ar2

array([[ 1.2137306 ,  1.03091598],
       [ 1.35580934,  1.05183255],
       [ 1.5568598 ,  1.20043567],
       [ 1.46326386,  1.03040233],
       [ 1.95281784,  1.49773222]])