# Session 1

### What is Numpy ?

[http://www.numpy.org/](http://www.numpy.org/)

[Reference](https://docs.scipy.org/doc/numpy/reference/)

- Numpy "numeric processing library"

**List and Array in Python**

In [1]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [2]:
import array

In [3]:
array.array('i', [1, 2, 3, 4])

array('i', [1, 2, 3, 4])

In [4]:
[1, 'a']

[1, 'a']

In [5]:
array.array('i', [1, 'a'])

TypeError: an integer is required (got type str)

**Numpy array**

In [6]:
import numpy

In [7]:
numpy.array([1, 3, 4, 5])

array([1, 3, 4, 5])

In [9]:
from numpy import array

In [10]:
array([1, 2, 4, 5, 7.1])

array([1. , 2. , 4. , 5. , 7.1])

In [11]:
from array import array

In [13]:
array('f', [3, 4, 5, 6.1])

array('f', [3.0, 4.0, 5.0, 6.099999904632568])

**Numpy with alias**

In [14]:
import numpy as np

In [15]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [16]:
lst = [1, 2, 3, 4]

In [17]:
nplst = np.array(lst)

In [18]:
type(lst)

list

In [19]:
type(nplst)

numpy.ndarray

In [20]:
nplst

array([1, 2, 3, 4])

In [21]:
nplst.dtype

dtype('int64')

In [22]:
type(1)

int

In [23]:
nplst.shape

(4,)

In [24]:
nplst.size

4

In [25]:
nplst.ndim

1

In [26]:
np.arange(0, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
range(0, 9)

range(0, 9)

**array methods**

In [30]:
arr1 = np.arange(1, 15)

In [31]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
dir(arr1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [34]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr1.mean()

7.5

In [35]:
arr1.max()

14

In [36]:
arr1.min()

1

In [37]:
arr1.std()

4.031128874149275

In [38]:
arr1.sum()

105

In [39]:
arr1.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105])

**numpy methods**

Random values

In [44]:
np.random.randint(9)

7

In [46]:
np.random.random()

0.6223861955957598

In [47]:
np.random.randn(10)

array([-0.53983871,  0.38534856,  0.63643565,  0.70304778, -0.92739172,
        0.8997801 ,  1.33567939, -0.35887849, -0.78339523, -0.72841617])

Linear values

In [48]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [49]:
np.linspace(0, 1, num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Trig functions**

In [50]:
np.sin(12)

-0.5365729180004349

In [51]:
np.cos(34)

-0.8485702747846052

In [52]:
np.tan(45)

1.6197751905438615

**constants**

In [53]:
np.pi

3.141592653589793

In [103]:
np.inf

inf

In [104]:
np.NaN

nan

In [105]:
np.NaN == np.NaN

False

In [106]:
None == None

True

In [107]:
np.inf == np.inf

True

In [63]:
data = np.linspace(-np.pi, np.pi)

In [64]:
data

array([-3.14159265, -3.01336438, -2.88513611, -2.75690784, -2.62867957,
       -2.5004513 , -2.37222302, -2.24399475, -2.11576648, -1.98753821,
       -1.85930994, -1.73108167, -1.60285339, -1.47462512, -1.34639685,
       -1.21816858, -1.08994031, -0.96171204, -0.83348377, -0.70525549,
       -0.57702722, -0.44879895, -0.32057068, -0.19234241, -0.06411414,
        0.06411414,  0.19234241,  0.32057068,  0.44879895,  0.57702722,
        0.70525549,  0.83348377,  0.96171204,  1.08994031,  1.21816858,
        1.34639685,  1.47462512,  1.60285339,  1.73108167,  1.85930994,
        1.98753821,  2.11576648,  2.24399475,  2.37222302,  2.5004513 ,
        2.62867957,  2.75690784,  2.88513611,  3.01336438,  3.14159265])

In [58]:
def add2(value):
    return value + 2

In [59]:
lst

[1, 2, 3, 4]

In [61]:
[add2(item) for item in lst]

[3, 4, 5, 6]

In [62]:
np.sin(12)

-0.5365729180004349

In [65]:
np.sin(data)

array([-1.22464680e-16, -1.27877162e-01, -2.53654584e-01, -3.75267005e-01,
       -4.90717552e-01, -5.98110530e-01, -6.95682551e-01, -7.81831482e-01,
       -8.55142763e-01, -9.14412623e-01, -9.58667853e-01, -9.87181783e-01,
       -9.99486216e-01, -9.95379113e-01, -9.74927912e-01, -9.38468422e-01,
       -8.86599306e-01, -8.20172255e-01, -7.40277997e-01, -6.48228395e-01,
       -5.45534901e-01, -4.33883739e-01, -3.15108218e-01, -1.91158629e-01,
       -6.40702200e-02,  6.40702200e-02,  1.91158629e-01,  3.15108218e-01,
        4.33883739e-01,  5.45534901e-01,  6.48228395e-01,  7.40277997e-01,
        8.20172255e-01,  8.86599306e-01,  9.38468422e-01,  9.74927912e-01,
        9.95379113e-01,  9.99486216e-01,  9.87181783e-01,  9.58667853e-01,
        9.14412623e-01,  8.55142763e-01,  7.81831482e-01,  6.95682551e-01,
        5.98110530e-01,  4.90717552e-01,  3.75267005e-01,  2.53654584e-01,
        1.27877162e-01,  1.22464680e-16])

In [66]:
np.cos(data)

array([-1.        , -0.99179001, -0.96729486, -0.92691676, -0.8713187 ,
       -0.80141362, -0.71834935, -0.6234898 , -0.51839257, -0.40478334,
       -0.28452759, -0.1595999 , -0.03205158,  0.09602303,  0.22252093,
        0.34536505,  0.46253829,  0.57211666,  0.67230089,  0.76144596,
        0.8380881 ,  0.90096887,  0.94905575,  0.98155916,  0.99794539,
        0.99794539,  0.98155916,  0.94905575,  0.90096887,  0.8380881 ,
        0.76144596,  0.67230089,  0.57211666,  0.46253829,  0.34536505,
        0.22252093,  0.09602303, -0.03205158, -0.1595999 , -0.28452759,
       -0.40478334, -0.51839257, -0.6234898 , -0.71834935, -0.80141362,
       -0.8713187 , -0.92691676, -0.96729486, -0.99179001, -1.        ])

In [68]:
nplst2 = np.array([[1, 2], [1, 2]])

In [71]:
nplst2

array([[1, 2],
       [1, 2]])

In [72]:
nplst2.shape

(2, 2)

In [73]:
nplst2.ndim

2

In [74]:
nplst2.size

4

In [75]:
nplst2.dtype

dtype('int64')

In [76]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
np.arange(0, 20).reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [78]:
np.arange(0, 20).reshape((5, 5))

ValueError: cannot reshape array of size 20 into shape (5,5)

In [79]:
np.arange(0, 20).reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
np.arange(0, 20).reshape((2, 2, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [82]:
np.arange(0, 21).reshape((1, 3, 7)).ndim

3

In [86]:
nplst3 = np.arange(0, 18).reshape((3, 3, 2))

In [87]:
nplst3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [88]:
nplst3.shape

(3, 3, 2)

In [90]:
nplst3.ndim

3

In [91]:
nplst3.size

18

In [92]:
nplst3.itemsize

8

In [93]:
np.array([1.2, 4]).itemsize

8

In [95]:
np.array(['a', 5])

array(['a', '5'], dtype='<U1')

In [96]:
np.array(['a', 5]).itemsize

4

In [97]:
np.array([True, False]).itemsize

1

In [98]:
nplst3.itemsize * nplst3.size

144

In [99]:
nplst4 = np.arange(0, 120).reshape((2, 3, 4, 5))

In [100]:
nplst4

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [101]:
np.array([1, 2, 3 ,4, 5, 6]).cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [102]:
np.array([1, 2, 3 ,4, 5, 6]).cumprod()

array([  1,   2,   6,  24, 120, 720])