# Session 3
---

In [1]:
import numpy as np

In [2]:
ar = np.arange(3, 32)

In [3]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

**np.where**

In [4]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are

In [5]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [6]:
np.where(ar < 10, 15, 18)

array([15, 15, 15, 15, 15, 15, 15, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18])

```python
x if condition else y
```

In [7]:
np.where(ar < 10, 'Yes', 'No')

array(['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'], dtype='<U3')

In [8]:
np.where(ar < 10, 'Y', 18)

array(['Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', '18', '18', '18', '18', '18',
       '18', '18', '18', '18', '18', '18', '18', '18', '18', '18', '18',
       '18', '18', '18', '18', '18', '18'], dtype='<U21')

In [9]:
np.where(ar < 10, 15)

ValueError: either both or neither of x and y should be given

In [12]:
ar

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [10]:
np.where(ar < 10)

(array([0, 1, 2, 3, 4, 5, 6]),)

In [11]:
type(np.where(ar < 10))

tuple

**np.any**

In [12]:
help(np.any)

Help on function any in module numpy.core.fromnumeric:

any(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (`axis` = `None`) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        

In [13]:
np.any([0, 1, 1, 1, 0])

True

In [14]:
np.any([False, True, False, True, True])

True

In [15]:
np.any([[True, False], [True, False]])

True

In [16]:
np.any([[True, True], [False, False]])

True

In [19]:
np.any([[True, True], [False, False]], axis=0)

array([ True,  True])

In [20]:
np.any([[True, True], [False, False]], axis=1)

array([ True, False])

**np.all**

In [21]:
help(np.all)

Help on function all in module numpy.core.fromnumeric:

all(a, axis=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Test whether all array elements along a given axis evaluate to True.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical AND reduction is performed.
        The default (`axis` = `None`) is to perform a logical AND over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.
        It must have the same shape as the expected output and its
        type is

In [22]:
np.all([[True, False], [True, False]])

False

In [23]:
np.all([[True, False], [True, False]], axis=0)

array([ True, False])

In [25]:
np.all([[True, False], [True, False]], axis=1)

array([False, False])

In [27]:
np.all(~np.array([False, False, False]))

True

In [28]:
not np.all(np.array([False, False, False]))

True

In [29]:
~np.array([False, False, False])

array([ True,  True,  True])

In [30]:
np.all(np.array([False, True, False]))

False

In [31]:
not np.all(np.array([False, True, False]))

True

In [32]:
np.all(~np.array([False, True, False]))

False

In [33]:
~np.all(np.array([False, False, False]))

True

**axis**

In [34]:
ar2 = np.arange(0, 12).reshape((3, 4))

In [35]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
ar2.shape

(3, 4)

In [36]:
ar2.sum()

66

In [37]:
ar2.sum(axis=1)

array([ 6, 22, 38])

In [39]:
ar2.sum(axis=0)

array([12, 15, 18, 21])

In [40]:
ar3 = np.arange(0,12).reshape((2,2,3))

In [41]:
ar3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [42]:
ar3.shape

(2, 2, 3)

In [44]:
ar3.sum(axis=2)

array([[ 3, 12],
       [21, 30]])

In [45]:
ar3.sum(axis=1)

array([[ 3,  5,  7],
       [15, 17, 19]])

In [46]:
ar3.sum(axis=0)

array([[ 6,  8, 10],
       [12, 14, 16]])

In [47]:
ar4 = np.arange(0, 16).reshape((2,2,2,2))

In [48]:
ar4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [49]:
ar4.sum(axis=0)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [50]:
ar4.sum(axis=1)

array([[[ 4,  6],
        [ 8, 10]],

       [[20, 22],
        [24, 26]]])

In [51]:
ar4.sum(axis=2)

array([[[ 2,  4],
        [10, 12]],

       [[18, 20],
        [26, 28]]])

In [52]:
ar4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [53]:
ar4.sum(axis=3)

array([[[ 1,  5],
        [ 9, 13]],

       [[17, 21],
        [25, 29]]])

In [52]:
ar4.sum(axis=3).shape

(2, 2, 2)

In [56]:
help(np.add.reduce)

Help on built-in function reduce:

reduce(...) method of numpy.ufunc instance
    reduce(a, axis=0, dtype=None, out=None, keepdims=False)
    
    Reduces `a`'s dimension by one, by applying ufunc along one axis.
    
    Let :math:`a.shape = (N_0, ..., N_i, ..., N_{M-1})`.  Then
    :math:`ufunc.reduce(a, axis=i)[k_0, ..,k_{i-1}, k_{i+1}, .., k_{M-1}]` =
    the result of iterating `j` over :math:`range(N_i)`, cumulatively applying
    ufunc to each :math:`a[k_0, ..,k_{i-1}, j, k_{i+1}, .., k_{M-1}]`.
    For a one-dimensional array, reduce produces results equivalent to:
    ::
    
     r = op.identity # op = ufunc
     for i in range(len(A)):
       r = op(r, A[i])
     return r
    
    For example, add.reduce() is equivalent to sum().
    
    Parameters
    ----------
    a : array_like
        The array to act on.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a reduction is performed.
        The default (`axis` = 0) is perform a reduction o

In [54]:
np.add.reduce(np.array([1, 2, 3]))

6

In [55]:
np.add(np.array([1, 2, 3]), 2)

array([3, 4, 5])

In [57]:
help(np.prod)

Help on function prod in module numpy.core.fromnumeric:

prod(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the product of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a product is performed.  The default,
        axis=None, will calculate the product of all the elements in the
        input array. If axis is negative it counts from the last to the
        first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a product is performed on all of the
        axes specified in the tuple instead of a single axis or all the
        axes as before.
    dtype : dtype, optional
        The type of the returned array, as well as of the accumulator in
        which the elements are multiplied.  The dtype of `a` is used by
        default unless `a` has an integer dtype of les

In [60]:
help(np.log10)

Help on ufunc object:

log10 = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array

In [59]:
np.info(np.log10)

log10(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the base 10 logarithm of the input array, element-wise.

Parameters
----------
x : array_like
    Input values.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray
    The logarithm to the base 10 of `x`, element-wise. NaNs are
    returned where x is negative.

See Also
--------
emath.log10

N

In [61]:
np.log10([567])

array([2.75358306])

In [63]:
np.log10(1287648359798234792387492384923849243)

AttributeError: 'int' object has no attribute 'log10'

In [64]:
np.log10(np.float64(1287648359798234792387492384923849243))

36.10979727897904

In [65]:
np.int64

numpy.int64

In [66]:
np.log10(np.float64(29348792384921384792384921387492834928374928734928734928734928734928734987234987234987239487293487293487293847))

109.46759023603151

**vectorize**

In [67]:
def add_numbers(x):
    return x + x

In [68]:
add_numbers(2)

4

In [70]:
(lambda x: x + x)

<function __main__.<lambda>(x)>

In [71]:
(lambda x: x + x)(2)

4

In [72]:
add_two_numbers = lambda x: x + x

In [73]:
add_two_numbers(2)

4

In [74]:
np.sin(np.array([2, 3]))

array([0.90929743, 0.14112001])

In [75]:
add_three = lambda x: x + 3

In [76]:
add_three(np.array([2, 3]))

array([5, 6])

In [77]:
add_number = lambda x, y: x + y

In [78]:
add_number(np.array([2, 3]), 5)

array([7, 8])

### Notes

numpy has __vectorize__ function just like __map__ python function

```python
import numpy as np

vfunc = np.vectorize(lambda x, y: x % y == 0)

vfunc(np.array([2, 3, 4, 5, 6, 7]), 2)

>>> np.array([True, False, True, False, True, False])
```

Above example vfunc returns array, *vfunc is much like np.sin/np.cos etc*


```python
def sum(a, b):
    return a + b

lambda a, b: a + b
```

**reduce**
```python

np.add.reduce(np.array([1, 2, 3]))
>>> 6
```

### Find primes numbers between 1 and 1000, ( use only numpy array, slicing, masking etc. )