# Datascience Introduction
---

## What is datascience?
---
- Analysis/Visualization/Machine Learning?

## References for requirements

### Python

- [http://greenteapress.com/wp/think-python-2e/](http://greenteapress.com/wp/think-python-2e/)

### Statistics
- [https://openstax.org/](https://openstax.org/)
- [https://www.openintro.org/stat/](https://www.openintro.org/stat/)
- [http://greenteapress.com/thinkstats/](http://greenteapress.com/thinkstats/)

### HTML
- [https://www.w3schools.com/html/](https://www.w3schools.com/html/)

### Videos
- [https://www.khanacademy.org/](https://www.khanacademy.org/)

## Libraries
---

- Numpy
- Pandas
- Matplotlib/Seaborn
- BeautifulSoup
- Requests
- Scikit-Learn

In [10]:
import numpy as np

In [11]:
import math

In [12]:
math.sqrt(32)

5.656854249492381

In [13]:
import numpy

In [14]:
numpy.array([12, 34])

array([12, 34])

In [15]:
import numpy as np

In [16]:
import os

In [17]:
os.path.join

<function posixpath.join>

In [18]:
os.path.join('hello', 'world')

'hello/world'

In [19]:
from os import path

In [20]:
path.join('one', 'two')

'one/two'

In [22]:
'\'

SyntaxError: EOL while scanning string literal (<ipython-input-22-219d1854b459>, line 1)

In [23]:
'\\'

'\\'

In [24]:
from os.path import join

In [25]:
join('a', 'b')

'a/b'

In [27]:
from urllib.parse import urljoin

In [28]:
urljoin('http://example.net', 'faq.html')

'http://example.net/faq.html'

In [29]:
urljoin('http://example.net/home.html', 'faq.html')

'http://example.net/faq.html'

In [30]:
join('http://example.net/home.html', 'faq.html')

'http://example.net/home.html/faq.html'

In [31]:
urljoin('a', 'b')

'b'

In [32]:
from urllib.parse import urljoin as join

In [33]:
join

<function urllib.parse.urljoin>

In [34]:
import os

In [35]:
import numpy as np

In [37]:
import urllib.parse as uparse

In [38]:
uparse.urljoin

<function urllib.parse.urljoin>

In [39]:
np.array([1, 2, 3])

array([1, 2, 3])

In [40]:
np.array([1, 1.3, 6])

array([ 1. ,  1.3,  6. ])

In [41]:
np.array([3, 'a', 9.2])

array(['3', 'a', '9.2'],
      dtype='<U21')

In [42]:
np.array([1, 2, 3]).dtype

dtype('int64')

In [43]:
np.array([[1, 4, 5, 6, 7], [3, 4, 6, 9, 1]])

array([[1, 4, 5, 6, 7],
       [3, 4, 6, 9, 1]])

In [44]:
np.arange(0, 18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [45]:
np.arange(0, 18).reshape((2, 3, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [46]:
%timeit [x ** 2 for x in range(0, 999)]

410 µs ± 5.34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [47]:
%timeit np.arange(0, 999) * 2

7.89 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
[x ** 2 for x in range(0, 999)]

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 2

In [49]:
range(0, 999) * 2

TypeError: unsupported operand type(s) for *: 'range' and 'int'

In [50]:
np.arange(0, 999) * 2

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3