# Session 1

### What is Numpy ?

[http://www.numpy.org/](http://www.numpy.org/)

[Reference](https://docs.scipy.org/doc/numpy/reference/)

- Numpy "numeric processing library"

**List and Array in Python**

In [1]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [2]:
import array

In [3]:
array.array('i', [1, 2, 3, 4])

array('i', [1, 2, 3, 4])

In [4]:
[1, 'a']

[1, 'a']

In [5]:
array.array('i', [1, 'a'])

TypeError: an integer is required (got type str)

**Numpy Array**

In [6]:
import numpy as np

In [7]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
lst = [1, 2, 3, 4]

In [9]:
nplst = np.array(lst)

In [10]:
type(lst)

list

In [11]:
type(nplst)

numpy.ndarray

In [12]:
nplst

array([1, 2, 3, 4])

In [13]:
nplst.dtype

dtype('int64')

In [14]:
nplst.shape

(4,)

In [15]:
nplst.size

4

In [16]:
dir(nplst)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [17]:
nplst.ndim

1

In [18]:
np.arange(0, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
nplst2 = np.array([[1, 2], [1, 2]])

In [20]:
nplst2.shape

(2, 2)

In [21]:
nplst2.ndim

2

In [22]:
nplst2.size

4

In [23]:
np.array([1.9, 3, 4, 5, 6, 7, 7]).dtype

dtype('float64')

In [24]:
np.arange(0, 21).reshape((1, 3, 7))

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]]])

In [25]:
nplst2

array([[1, 2],
       [1, 2]])

In [26]:
np.arange(0, 6).reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [27]:
np.arange(0, 21).reshape((1, 3, 7)).ndim

3

In [30]:
nplst3 = np.arange(0, 24).reshape((2, 3, 4))

In [31]:
nplst3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
np.array([ 0,  1,  2,  3])

array([0, 1, 2, 3])

In [34]:
nplst3.ndim

3

In [35]:
nplst3.size

24

In [36]:
nplst3.itemsize

8

In [37]:
np.array([1.2, 4]).itemsize

8

In [38]:
np.array(['a', 5]).itemsize

4

In [39]:
nplst3.itemsize * nplst3.size

192

In [41]:
import math
math.factorial(5)

120

In [42]:
nplst4 = np.arange(0, 120).reshape((2, 3, 4, 5))

In [43]:
nplst4

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [49]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [50]:
r1 = np.random.random(50)

In [51]:
r1

array([ 0.19065408,  0.47271553,  0.31435588,  0.99514351,  0.64882225,
        0.97013548,  0.62269777,  0.06577482,  0.59581387,  0.23474529,
        0.56245139,  0.69004993,  0.35320854,  0.75322651,  0.4259049 ,
        0.03399412,  0.44794556,  0.90461601,  0.00121442,  0.11874539,
        0.87043549,  0.90681878,  0.23407314,  0.94576031,  0.21579124,
        0.93100918,  0.62942567,  0.10791967,  0.90057681,  0.76450563,
        0.81873542,  0.46758653,  0.41822933,  0.81104705,  0.38499521,
        0.23123501,  0.15813623,  0.09845818,  0.11073125,  0.6182875 ,
        0.45269537,  0.83620174,  0.60327785,  0.02958353,  0.78395539,
        0.36687838,  0.6311978 ,  0.22649117,  0.79700204,  0.10655783])

In [52]:
r2 = np.random.random((10, 5))

In [53]:
r2

array([[ 0.6802055 ,  0.30846518,  0.57640778,  0.13480251,  0.62841433],
       [ 0.42031306,  0.18268425,  0.51548657,  0.42861202,  0.05492062],
       [ 0.55636881,  0.86596882,  0.78810128,  0.70045986,  0.5393478 ],
       [ 0.39542386,  0.67871664,  0.71224414,  0.16706382,  0.98309272],
       [ 0.65838392,  0.53671845,  0.20402906,  0.0594289 ,  0.24017276],
       [ 0.53445932,  0.55120333,  0.88540864,  0.04506883,  0.88747073],
       [ 0.13136441,  0.67112018,  0.29347875,  0.64495204,  0.50787992],
       [ 0.04417502,  0.54519298,  0.43869638,  0.56209499,  0.90428069],
       [ 0.56205158,  0.48586485,  0.53263522,  0.85457116,  0.69505987],
       [ 0.68178681,  0.60075022,  0.31932407,  0.38578713,  0.14357956]])

In [54]:
r1.min()

0.0012144221880747708

In [55]:
r1.max()

0.9951435050302353

In [56]:
r2.min()

0.044175015027219322

In [57]:
r2.max()

0.98309271732147596

In [58]:
r1.mean()

0.49719627958698082

In [59]:
r2.mean()

0.49848178670001253

In [60]:
r1.sum()

24.859813979349042

In [61]:
r2.sum()

24.924089335000627

In [62]:
dir(r1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [63]:
r1.cumsum()

array([  0.19065408,   0.66336961,   0.9777255 ,   1.972869  ,
         2.62169125,   3.59182673,   4.2145245 ,   4.28029932,
         4.8761132 ,   5.11085849,   5.67330988,   6.36335981,
         6.71656835,   7.46979486,   7.89569975,   7.92969387,
         8.37763943,   9.28225544,   9.28346986,   9.40221525,
        10.27265074,  11.17946952,  11.41354266,  12.35930297,
        12.57509421,  13.50610339,  14.13552906,  14.24344872,
        15.14402553,  15.90853117,  16.72726659,  17.19485311,
        17.61308245,  18.4241295 ,  18.80912471,  19.04035972,
        19.19849595,  19.29695414,  19.40768539,  20.02597289,
        20.47866825,  21.31486999,  21.91814784,  21.94773137,
        22.73168676,  23.09856514,  23.72976294,  23.95625412,
        24.75325615,  24.85981398])

In [64]:
r2.cumsum()

array([  0.6802055 ,   0.98867068,   1.56507846,   1.69988097,
         2.3282953 ,   2.74860836,   2.93129261,   3.44677918,
         3.8753912 ,   3.93031182,   4.48668063,   5.35264945,
         6.14075073,   6.84121059,   7.38055839,   7.77598225,
         8.45469889,   9.16694303,   9.33400685,  10.31709957,
        10.97548349,  11.51220194,  11.716231  ,  11.7756599 ,
        12.01583266,  12.55029198,  13.10149531,  13.98690395,
        14.03197278,  14.91944351,  15.05080792,  15.72192809,
        16.01540684,  16.66035888,  17.1682388 ,  17.21241381,
        17.7576068 ,  18.19630318,  18.75839816,  19.66267886,
        20.22473044,  20.71059529,  21.24323051,  22.09780167,
        22.79286154,  23.47464835,  24.07539857,  24.39472264,
        24.78050977,  24.92408934])

In [66]:
r1.cumprod()

array([  1.90654085e-01,   9.01251468e-02,   2.83313700e-02,
         2.81937788e-02,   1.82927510e-02,   1.77464467e-02,
         1.10506729e-02,   7.26856034e-04,   4.33070909e-04,
         1.01661357e-04,   5.71795717e-05,   3.94567594e-05,
         1.39364645e-05,   1.04973145e-05,   4.47085763e-06,
         1.51982849e-07,   6.80800424e-08,   6.15862962e-08,
         7.47917646e-11,   8.88117721e-12,   7.73049182e-12,
         7.01015515e-12,   1.64088903e-12,   1.55188772e-12,
         3.34883780e-13,   3.11779873e-13,   1.96242255e-13,
         2.11783991e-14,   1.90727750e-14,   1.45812440e-14,
         1.19381809e-14,   5.58213255e-15,   2.33461158e-15,
         1.89347984e-15,   7.28980667e-16,   1.68565851e-16,
         2.66563690e-17,   2.62453768e-18,   2.90618333e-19,
         1.79685683e-19,   8.13428765e-20,   6.80190548e-20,
         4.10343890e-20,   1.21394193e-21,   9.51676323e-22,
         3.49149468e-22,   2.20382377e-22,   4.99146633e-23,
         3.97820882e-23,

In [67]:
np.array([1, 2, 3 ,4, 5, 6]).cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [68]:
0.07 * 0.19

0.013300000000000001

In [70]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    If positive, int_like or int-convertible arguments are provided,
    `randn` generates an array of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1 (if any of the :math:`d_i` are
    floats, they are first converted to integers by truncation). A single
    float randomly sampled from the distribution is returned if no
    argument is provided.
    
    This is a convenience function.  If you want an interface that takes a
    tuple as the first argument, use `numpy.random.standard_normal` instead.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should be all positive.
        If no argument is given a single Python float is ret

In [71]:
np.random.randn()

-0.29509700752603196

In [72]:
np.random.randn(2)

array([ 0.66210546, -1.00007131])

In [73]:
np.random.randn(2, 3)

array([[-1.73167637, -0.5181285 , -0.30863707],
       [ 0.39988627, -1.44510305,  0.48052076]])

In [74]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [75]:
r4 = np.random.randint(10, 30)

In [76]:
r4

12

In [77]:
r4 = np.random.randint(10, 30, size=25)

In [78]:
r4

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14])

In [79]:
r4.mean()

18.960000000000001

In [80]:
np.median(r4)

19.0

In [81]:
r4.std()

5.8888368970451204

In [82]:
np.var(r4)

34.678399999999996

In [83]:
help(np.var)

Help on function var in module numpy.core.fromnumeric:

var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<class 'numpy._globals._NoValue'>)
    Compute the variance along the specified axis.
    
    Returns the variance of the array elements, a measure of the spread of a
    distribution.  The variance is computed for the flattened array by
    default, otherwise over the specified axis.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose variance is desired.  If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the variance is computed.  The default is to
        compute the variance of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a variance is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computin

In [84]:
r4

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14])

In [85]:
r4.mean() - r4

array([-2.04, -9.04, -5.04,  8.96, -0.04, -9.04,  6.96,  2.96, -4.04,
       -5.04,  4.96,  7.96,  3.96,  1.96,  8.96,  4.96,  6.96, -9.04,
       -0.04, -5.04,  1.96, -5.04, -6.04, -6.04,  4.96])

In [86]:
r4 * 2

array([42, 56, 48, 20, 38, 56, 24, 32, 46, 48, 28, 22, 30, 34, 20, 28, 24,
       56, 38, 48, 34, 48, 50, 50, 28])

In [87]:
r4 + 1

array([22, 29, 25, 11, 20, 29, 13, 17, 24, 25, 15, 12, 16, 18, 11, 15, 13,
       29, 20, 25, 18, 25, 26, 26, 15])

In [88]:
np.add(r4, 1)

array([22, 29, 25, 11, 20, 29, 13, 17, 24, 25, 15, 12, 16, 18, 11, 15, 13,
       29, 20, 25, 18, 25, 26, 26, 15])

In [89]:
np.subtract(r4, r4.mean())

array([ 2.04,  9.04,  5.04, -8.96,  0.04,  9.04, -6.96, -2.96,  4.04,
        5.04, -4.96, -7.96, -3.96, -1.96, -8.96, -4.96, -6.96,  9.04,
        0.04,  5.04, -1.96,  5.04,  6.04,  6.04, -4.96])

In [91]:
help(np.subtract)

Help on ufunc object:

subtract = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate ar

In [92]:
np.subtract(r4.mean(), r4)

array([-2.04, -9.04, -5.04,  8.96, -0.04, -9.04,  6.96,  2.96, -4.04,
       -5.04,  4.96,  7.96,  3.96,  1.96,  8.96,  4.96,  6.96, -9.04,
       -0.04, -5.04,  1.96, -5.04, -6.04, -6.04,  4.96])

In [94]:
r4

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14])

In [96]:
len(r4)

25

In [97]:
np.append(r4, 17)

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14, 17])

In [98]:
r4

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14])

In [99]:
r4 = np.append(r4, 17)

In [100]:
np.split(r4, 2)

[array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15]),
 array([17, 10, 14, 12, 28, 19, 24, 17, 24, 25, 25, 14, 17])]

In [101]:
r41, r42 = np.split(r4, 2)

In [102]:
r41

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15])

In [103]:
r42

array([17, 10, 14, 12, 28, 19, 24, 17, 24, 25, 25, 14, 17])

In [104]:
r41 + r42

array([38, 38, 38, 22, 47, 47, 36, 33, 47, 49, 39, 25, 32])

In [105]:
[1, 2, 3] + [3, 4, 5]

[1, 2, 3, 3, 4, 5]

In [107]:
np.concatenate((r42, r41))

array([17, 10, 14, 12, 28, 19, 24, 17, 24, 25, 25, 14, 17, 21, 28, 24, 10,
       19, 28, 12, 16, 23, 24, 14, 11, 15])

In [108]:
r4

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14, 17])

In [110]:
help(np.hsplit)

Help on function hsplit in module numpy.lib.shape_base:

hsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays horizontally (column-wise).
    
    Please refer to the `split` documentation.  `hsplit` is equivalent
    to `split` with ``axis=1``, the array is always split along the second
    axis regardless of the array dimension.
    
    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[  0.,   1.,   2.,   3.],
           [  4.,   5.,   6.,   7.],
           [  8.,   9.,  10.,  11.],
           [ 12.,  13.,  14.,  15.]])
    >>> np.hsplit(x, 2)
    [array([[  0.,   1.],
           [  4.,   5.],
           [  8.,   9.],
           [ 12.,  13.]]),
     array([[  2.,   3.],
           [  6.,   7.],
           [ 10.,  11.],
           [ 14.,  15.]])]
    >>> np.hsplit(x, np.array([3, 6]))
    [array([[  0.,   1.,   2.],
           [

In [114]:
np.linspace(1, 20, num=16)

array([  1.        ,   2.26666667,   3.53333333,   4.8       ,
         6.06666667,   7.33333333,   8.6       ,   9.86666667,
        11.13333333,  12.4       ,  13.66666667,  14.93333333,
        16.2       ,  17.46666667,  18.73333333,  20.        ])

In [115]:
np.linspace(1, 50, num=32)

array([  1.        ,   2.58064516,   4.16129032,   5.74193548,
         7.32258065,   8.90322581,  10.48387097,  12.06451613,
        13.64516129,  15.22580645,  16.80645161,  18.38709677,
        19.96774194,  21.5483871 ,  23.12903226,  24.70967742,
        26.29032258,  27.87096774,  29.4516129 ,  31.03225806,
        32.61290323,  34.19354839,  35.77419355,  37.35483871,
        38.93548387,  40.51612903,  42.09677419,  43.67741935,
        45.25806452,  46.83870968,  48.41935484,  50.        ])

In [119]:
np.linspace(1, 10, num=5)

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [120]:
r5 = np.linspace(1, 50, num=32)

In [121]:
r5

array([  1.        ,   2.58064516,   4.16129032,   5.74193548,
         7.32258065,   8.90322581,  10.48387097,  12.06451613,
        13.64516129,  15.22580645,  16.80645161,  18.38709677,
        19.96774194,  21.5483871 ,  23.12903226,  24.70967742,
        26.29032258,  27.87096774,  29.4516129 ,  31.03225806,
        32.61290323,  34.19354839,  35.77419355,  37.35483871,
        38.93548387,  40.51612903,  42.09677419,  43.67741935,
        45.25806452,  46.83870968,  48.41935484,  50.        ])

In [125]:
r6 = np.round(r5)

In [126]:
r6

array([  1.,   3.,   4.,   6.,   7.,   9.,  10.,  12.,  14.,  15.,  17.,
        18.,  20.,  22.,  23.,  25.,  26.,  28.,  29.,  31.,  33.,  34.,
        36.,  37.,  39.,  41.,  42.,  44.,  45.,  47.,  48.,  50.])

In [127]:
r6 = r6.reshape((4, 8))

In [128]:
r6

array([[  1.,   3.,   4.,   6.,   7.,   9.,  10.,  12.],
       [ 14.,  15.,  17.,  18.,  20.,  22.,  23.,  25.],
       [ 26.,  28.,  29.,  31.,  33.,  34.,  36.,  37.],
       [ 39.,  41.,  42.,  44.,  45.,  47.,  48.,  50.]])

In [129]:
np.split(r6, 2)

[array([[  1.,   3.,   4.,   6.,   7.,   9.,  10.,  12.],
        [ 14.,  15.,  17.,  18.,  20.,  22.,  23.,  25.]]),
 array([[ 26.,  28.,  29.,  31.,  33.,  34.,  36.,  37.],
        [ 39.,  41.,  42.,  44.,  45.,  47.,  48.,  50.]])]

In [130]:
np.hsplit(r6, 2)

[array([[  1.,   3.,   4.,   6.],
        [ 14.,  15.,  17.,  18.],
        [ 26.,  28.,  29.,  31.],
        [ 39.,  41.,  42.,  44.]]), array([[  7.,   9.,  10.,  12.],
        [ 20.,  22.,  23.,  25.],
        [ 33.,  34.,  36.,  37.],
        [ 45.,  47.,  48.,  50.]])]

In [132]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [133]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [134]:
# identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [135]:
help(np.full)

Help on function full in module numpy.core.numeric:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of in

In [136]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [137]:
r4

array([21, 28, 24, 10, 19, 28, 12, 16, 23, 24, 14, 11, 15, 17, 10, 14, 12,
       28, 19, 24, 17, 24, 25, 25, 14, 17])

In [138]:
np.sort(r4)

array([10, 10, 11, 12, 12, 14, 14, 14, 15, 16, 17, 17, 17, 19, 19, 21, 23,
       24, 24, 24, 24, 25, 25, 28, 28, 28])

In [139]:
np.sqrt(r4)

array([ 4.58257569,  5.29150262,  4.89897949,  3.16227766,  4.35889894,
        5.29150262,  3.46410162,  4.        ,  4.79583152,  4.89897949,
        3.74165739,  3.31662479,  3.87298335,  4.12310563,  3.16227766,
        3.74165739,  3.46410162,  5.29150262,  4.35889894,  4.89897949,
        4.12310563,  4.89897949,  5.        ,  5.        ,  3.74165739,
        4.12310563])

In [140]:
np.sin(r4)

array([ 0.83665564,  0.27090579, -0.90557836, -0.54402111,  0.14987721,
        0.27090579, -0.53657292, -0.28790332, -0.8462204 , -0.90557836,
        0.99060736, -0.99999021,  0.65028784, -0.96139749, -0.54402111,
        0.99060736, -0.53657292,  0.27090579,  0.14987721, -0.90557836,
       -0.96139749, -0.90557836, -0.13235175, -0.13235175,  0.99060736,
       -0.96139749])

In [141]:
np.cos(r4)

array([-0.54772926, -0.96260587,  0.42417901, -0.83907153,  0.98870462,
       -0.96260587,  0.84385396, -0.95765948, -0.53283302,  0.42417901,
        0.13673722,  0.0044257 , -0.75968791, -0.27516334, -0.83907153,
        0.13673722,  0.84385396, -0.96260587,  0.98870462,  0.42417901,
       -0.27516334,  0.42417901,  0.99120281,  0.99120281,  0.13673722,
       -0.27516334])

In [142]:
np.log(r4)

array([ 3.04452244,  3.33220451,  3.17805383,  2.30258509,  2.94443898,
        3.33220451,  2.48490665,  2.77258872,  3.13549422,  3.17805383,
        2.63905733,  2.39789527,  2.7080502 ,  2.83321334,  2.30258509,
        2.63905733,  2.48490665,  3.33220451,  2.94443898,  3.17805383,
        2.83321334,  3.17805383,  3.21887582,  3.21887582,  2.63905733,
        2.83321334])

In [143]:
np.log(np.array([1, 3, 4, 9.8, 'a']))

TypeError: ufunc 'log' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [144]:
np.sin(np.array([1, 3, 4, 9.8, 'a']))

TypeError: ufunc 'sin' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [145]:
np.NaN

nan

In [146]:
np.inf

inf

In [147]:
np.array([1, 2, 3, np.NaN])

array([  1.,   2.,   3.,  nan])

In [148]:
np.log(np.array([1, 2, 3, np.NaN]))

array([ 0.        ,  0.69314718,  1.09861229,         nan])

In [155]:
[x if not str(x).isalpha() else np.NaN for x in [1, 3, 4, 9.8, 'a']]

[1, 3, 4, 9.8, nan]

In [152]:
dir('')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

```python
x = 1
if y == 3:
    x = y
else:
    x = 0

x = y if y == 3 else 0
```