# Working with Features
---

### Categorical features

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()

In [2]:
sns.load_dataset?

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load a dataset from the online repository (requires internet).

Parameters
----------
name : str
    Name of the dataset (`name`.csv on
    https://github.com/mwaskom/seaborn-data).  You can obtain list of
    available datasets using :func:`get_dataset_names`
cache : boolean, optional
    If True, then cache data locally and use the cache on subsequent calls
data_home : string, optional
    The directory in which to cache data. By default, uses ~/seaborn-data/
kws : dict, optional
    Passed to pandas.read_csv
File:      ~/miniconda3/envs/pyml/lib/python3.7/site-packages/seaborn/utils.py
Type:      function


In [48]:
data = [
    {"price": 8_500_000, "rooms": 3, "loc": "Kathmandu"},
    {"price": 7_000_000, "rooms": 4, "loc": "Biratnagar"},
    {"price": 9_850_000, "rooms": 3, "loc": "Pokhara"},
    {"price": 7_500_000, "rooms": 5, "loc": "Birgunj"},
    {"price": 5_000_000, "rooms": 3, "loc": "Birgunj"},
]

In [49]:
pd.DataFrame(data)

loc    price  rooms
0   Kathmandu  8500000      3
1  Biratnagar  7000000      4
2     Pokhara  9850000      3
3     Birgunj  7500000      5
4     Birgunj  5000000      3

In [4]:
from sklearn.feature_extraction import DictVectorizer

In [5]:
DictVectorizer?

Init signature:
DictVectorizer(
    dtype=<class 'numpy.float64'>,
    separator='=',
    sparse=True,
    sort=True,
)
Docstring:     
Transforms lists of feature-value mappings to vectors.

This transformer turns lists of mappings (dict-like objects) of feature
names to feature values into Numpy arrays or scipy.sparse matrices for use
with scikit-learn estimators.

When feature values are strings, this transformer will do a binary one-hot
(aka one-of-K) coding: one boolean-valued feature is constructed for each
of the possible string values that the feature can take on. For instance,
a feature "f" that can take on the values "ham" and "spam" will become two
features in the output, one signifying "f=ham", the other "f=spam".

However, note that this transformer will only do a binary one-hot encoding
when feature values are of type string. If categorical features are
represented as numeric values such as int, the DictVectorizer can be
followed by :class:`sklearn.preprocessing.OneHotEnc

In [50]:
vec = DictVectorizer(sparse=False, dtype=int)
vec_1 = vec.fit_transform(data)
vec_1

array([[      0,       0,       1,       0, 8500000,       3],
       [      1,       0,       0,       0, 7000000,       4],
       [      0,       0,       0,       1, 9850000,       3],
       [      0,       1,       0,       0, 7500000,       5],
       [      0,       1,       0,       0, 5000000,       3]],
      dtype=int64)

In [7]:
vec.feature_names_

['loc=Biratnagar',
 'loc=Birgunj',
 'loc=Kathmandu',
 'loc=Pokhara',
 'price',
 'rooms']

In [8]:
vec.get_feature_names()

['loc=Biratnagar',
 'loc=Birgunj',
 'loc=Kathmandu',
 'loc=Pokhara',
 'price',
 'rooms']

In [51]:
pd.DataFrame(vec_1, columns=vec.get_feature_names())

loc=Biratnagar  loc=Birgunj  loc=Kathmandu  loc=Pokhara    price  rooms
0               0            0              1            0  8500000      3
1               1            0              0            0  7000000      4
2               0            0              0            1  9850000      3
3               0            1              0            0  7500000      5
4               0            1              0            0  5000000      3

### Text Features

In [9]:
sample = [
    "this is broken",
    "does not work after couple of days",
    "is not what is advertised"
]

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
CountVectorizer?

Init signature:
CountVectorizer(
    input='content',
    encoding='utf-8',
    decode_error='strict',
    strip_accents=None,
    lowercase=True,
    preprocessor=None,
    tokenizer=None,
    stop_words=None,
    token_pattern='(?u)\\b\\w\\w+\\b',
    ngram_range=(1, 1),
    analyzer='word',
    max_df=1.0,
    min_df=1,
    max_features=None,
    vocabulary=None,
    binary=False,
    dtype=<class 'numpy.int64'>,
)
Docstring:     
Convert a collection of text documents to a matrix of token counts

This implementation produces a sparse representation of the counts using
scipy.sparse.csr_matrix.

If you do not provide an a-priori dictionary and you do not use an analyzer
that does some kind of feature selection then the number of features will
be equal to the vocabulary size found by analyzing the data.

Read more in the :ref:`User Guide <text_feature_extraction>`.

Parameters
----------
input : string {'filename', 'file', 'content'}
    If 'filename', the sequence passed as an argume

In [12]:
vec = CountVectorizer()
X = vec.fit_transform(sample)
X

<3x12 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [16]:
X.toarray()

array([[0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0]], dtype=int64)

In [17]:
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

advertised  after  broken  couple  days  does  is  not  of  this  what  \
0           0      0       1       0     0     0   1    0   0     1     0   
1           0      1       0       1     1     1   0    1   1     0     0   
2           1      0       0       0     0     0   2    1   0     0     1   

   work  
0     0  
1     1  
2     0

#### TfIdf

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
vec = TfidfVectorizer()
X = vec.fit_transform(sample)
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

advertised     after    broken    couple      days      does        is  \
0    0.000000  0.000000  0.622766  0.000000  0.000000  0.000000  0.473630   
1    0.000000  0.389888  0.000000  0.389888  0.389888  0.389888  0.000000   
2    0.452123  0.000000  0.000000  0.000000  0.000000  0.000000  0.687703   

        not        of      this      what      work  
0  0.000000  0.000000  0.622766  0.000000  0.000000  
1  0.296520  0.389888  0.000000  0.000000  0.389888  
2  0.343851  0.000000  0.000000  0.452123  0.000000

### Derived feature

In [20]:
x = np.arange(1, 9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
X = x[:, np.newaxis]
X

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [22]:
from sklearn.preprocessing import PolynomialFeatures

In [23]:
PolynomialFeatures?

Init signature:
PolynomialFeatures(
    degree=2,
    interaction_only=False,
    include_bias=True,
    order='C',
)
Docstring:     
Generate polynomial and interaction features.

Generate a new feature matrix consisting of all polynomial combinations
of the features with degree less than or equal to the specified degree.
For example, if an input sample is two dimensional and of the form
[a, b], the degree-2 polynomial features are [1, a, b, a^2, ab, b^2].

Parameters
----------
degree : integer
    The degree of the polynomial features. Default = 2.

interaction_only : boolean, default = False
    If true, only interaction features are produced: features that are
    products of at most ``degree`` *distinct* input features (so not
    ``x[1] ** 2``, ``x[0] * x[2] ** 3``, etc.).

include_bias : boolean
    If True (default), then include a bias column, the feature in which
    all polynomial powers are zero (i.e. a column of ones - acts as an
    intercept term in a linear model).

or

In [26]:
poly = PolynomialFeatures(degree=2, include_bias=False)
X2 = poly.fit_transform(X)
X2

array([[ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.],
       [ 5., 25.],
       [ 6., 36.],
       [ 7., 49.],
       [ 8., 64.]])

In [27]:
poly = PolynomialFeatures(degree=2, include_bias=True)
X2_ = poly.fit_transform(X)
X2_

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.],
       [ 1.,  7., 49.],
       [ 1.,  8., 64.]])

In [28]:
poly = PolynomialFeatures(degree=3, include_bias=False)
X3 = poly.fit_transform(X)
X3

array([[  1.,   1.,   1.],
       [  2.,   4.,   8.],
       [  3.,   9.,  27.],
       [  4.,  16.,  64.],
       [  5.,  25., 125.],
       [  6.,  36., 216.],
       [  7.,  49., 343.],
       [  8.,  64., 512.]])

### Handling Missing data

In [29]:
nan = np.nan
XX = np.array([
    [nan, 0,   3],
    [4,   5,   9],
    [8,   7,   2],
    [4,   nan, 6],
    [8,   8,   1]
])
XX

array([[nan,  0.,  3.],
       [ 4.,  5.,  9.],
       [ 8.,  7.,  2.],
       [ 4., nan,  6.],
       [ 8.,  8.,  1.]])

In [30]:
yy = np.array([12, 18, -3, 3, -1])

In [31]:
from sklearn.preprocessing import Imputer

In [32]:
Imputer?

Init signature: Imputer(*args, **kwargs)
Docstring:     
Imputation transformer for completing missing values.

Read more in the :ref:`User Guide <imputation>`.

Parameters
----------
missing_values : integer or "NaN", optional (default="NaN")
    The placeholder for the missing values. All occurrences of
    `missing_values` will be imputed. For missing values encoded as np.nan,
    use the string value "NaN".

strategy : string, optional (default="mean")
    The imputation strategy.

    - If "mean", then replace missing values using the mean along
      the axis.
    - If "median", then replace missing values using the median along
      the axis.
    - If "most_frequent", then replace missing using the most frequent
      value along the axis.

axis : integer, optional (default=0)
    The axis along which to impute.

    - If `axis=0`, then impute along columns.
    - If `axis=1`, then impute along rows.

verbose : integer, optional (default=0)
    Controls the verbosity of the imp

In [33]:
Imputer(strategy="mean").fit_transform(XX)

array([[6., 0., 3.],
       [4., 5., 9.],
       [8., 7., 2.],
       [4., 5., 6.],
       [8., 8., 1.]])

In [34]:
Imputer(strategy="median").fit_transform(XX)

array([[6., 0., 3.],
       [4., 5., 9.],
       [8., 7., 2.],
       [4., 6., 6.],
       [8., 8., 1.]])

In [35]:
Imputer(strategy="most_frequent").fit_transform(XX)

array([[4., 0., 3.],
       [4., 5., 9.],
       [8., 7., 2.],
       [4., 0., 6.],
       [8., 8., 1.]])

### Feature pipeline

In [37]:
from sklearn.linear_model import LinearRegression

In [36]:
from sklearn.pipeline import make_pipeline

In [38]:
model = make_pipeline(
    Imputer(strategy="mean"),
    PolynomialFeatures(degree=2),
    LinearRegression()
)

In [39]:
model.fit(XX, yy)

Pipeline(memory=None,
         steps=[('imputer',
                 Imputer(axis=0, copy=True, missing_values='NaN',
                         strategy='mean', verbose=0)),
                ('polynomialfeatures',
                 PolynomialFeatures(degree=2, include_bias=True,
                                    interaction_only=False, order='C')),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [40]:
model.predict(XX)

array([12., 18., -3.,  3., -1.])