## Array Operations

Adding scalar to array

In [22]:
arr

array([1, 2, 3])

In [23]:
arr + 3

array([4, 5, 6])

*3 is added to every element of the array e.g*
$[1+3, 2+3, 3+3]$

Multiplying scalar to array

In [24]:
arr * 2

array([2, 4, 6])

Dividing scalar to array

In [25]:
arr / 3

array([0.33333333, 0.66666667, 1.        ])

> *Result: * $[1\div3, 2\div3, 3\div3]$

Substracting scalar to array

In [26]:
arr - 1

array([0, 1, 2])

Adding two arrays

In [27]:
arr1 = np.array([7, 8, 9])

In [28]:
arr + arr1

array([ 8, 10, 12])

*Adding two array is element wise operation*
$[1+7, 2+8, 3+9]$

Substracting two array

In [29]:
arr1 - arr

array([6, 6, 6])

Multiplying two array

In [30]:
arr1 * arr

array([ 7, 16, 27])

> *Result is * $[1*7, 2*8, 3*9]$

> *Remember operations between arrays is element wise, It is not the matrix multiplication ( vector product )*


Adding two array with different shape

In [31]:
np.array([1, 2]) + np.array([1, 2, 3])

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

*basically shape should be same*

In [32]:
np.array([[1, 2, 3], [1, 2, 3]]) + np.array([[1, 2], [1, 2], [1, 2]])

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

*both arrays have same size __6__ but different shape*

## Basic statistics

Let *temp_array* be random sample of temperatures

In [62]:
temp_array = np.random.rand(10) * 100

In [63]:
temp_array

array([30.25570646, 25.48568407, 11.42271952, 57.29264664,  9.08004099,
       18.04534503, 21.34729699, 90.38691494, 76.6396822 ,  4.48871022])

Datatype of temperatures

In [72]:
temp_array.dtype

dtype('float64')

Mean Temperature

In [64]:
temp_array.mean()

34.44447470652469

Maximum Temperature

In [65]:
temp_array.max()

90.38691494190716

Minimum Temperature

In [66]:
temp_array.min()

4.488710215075409

Sum of all temperatures

In [67]:
temp_array.sum()

344.4447470652469

Standard deviation

In [68]:
temp_array.std()

28.356670958813172

Cumulative sum

In [69]:
temp_array.cumsum()

array([ 30.25570646,  55.74139053,  67.16411005, 124.45675669,
       133.53679769, 151.58214272, 172.92943971, 263.31635465,
       339.95603685, 344.44474707])

Cumulative product

In [71]:
temp_array.cumprod()

array([3.02557065e+01, 7.71087376e+02, 8.80791482e+03, 5.04628752e+05,
       4.58204975e+06, 8.26846687e+07, 1.76509418e+09, 1.59541417e+11,
       1.22272035e+13, 5.48843734e+13])

## Array with various types

Array with integers

In [73]:
years = np.array([2011, 2012, 2013])

In [74]:
years.dtype

dtype('int64')

Size of each item in bytes

In [75]:
years.itemsize

8

Array with float

In [76]:
temp = np.random.rand(3)

In [77]:
temp.dtype

dtype('float64')

Size of each item in bytes

In [78]:
temp.itemsize

8

Array with chars (unicode)

In [79]:
chrs = np.array(['a', 'b', 'c'])

In [80]:
chrs.dtype

dtype('<U1')

Size of each item in bytes

In [81]:
chrs.itemsize

4

*Dot Product*

In [16]:
a.dot(b)

32

In [17]:
# only works in python 3.5 and above
a @ b

32

*fill into array*

In [48]:
b.fill(0)

In [49]:
b

array([0, 0, 0])

**Type cohersion**

In [50]:
a.dtype

dtype('int64')

In [51]:
a[0] = 2.3

In [52]:
a

array([2, 7, 3])

In [53]:
a[0] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

> *Since, a is of dtype int64. 2.3 is cast to int above*

*cannot change dtype of an ndarray*

In [ ]:
b.fill(1.1)

In [ ]:
b

In [ ]:
b.astype(np.float64)

In [ ]:
b.dtype

> *Same goes for fill*

### Array slicing

**array[lower:upper:step]**

- `lower` if ommitted defaults to 0
- `upper` if ommitted defaults to length of array
- `step`  if ommitted defaults to 1 

In [ ]:
a

In [ ]:
a[:]

In [ ]:
a[0:]

In [ ]:
a[:-1]

In [ ]:
a[:2]

In [ ]:
a[1:]

In [ ]:
a[::2]

In [ ]:
a[::-1]

In [ ]:
a[-2:]

**Cool tricks with array slicing**

*finding out mid point of every consecutive items in an array*

In [ ]:
aa = np.array([1, 2, 3, 5, 8, 13, 21, 34])

In [ ]:
aa[1:]

In [ ]:
aa[:-1]

In [ ]:
aa[1:] + aa[:-1]

In [ ]:
(aa[1:] + aa[:-1]) / 2