# Numpy
---

In [1]:
import numpy as np

## Converting shape of an array

In [2]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

Create 1-dimensional array

In [6]:
arr = np.arange(0, 12)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshape to new 2 dimensional array

In [8]:
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

*reshapes one array to another with given dimension in row, column format*

Reshape to new 3 dimensional array

In [9]:
arr.reshape(3, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

*reshapes one array to another with given dimension in depth, row, column format*

*size must be same after reshaping, cannot reshape to arbitrary size array*

In [10]:
arr.size

12

In [11]:
arr.reshape(3, 4).size

12

In [12]:
arr.reshape(3, 2, 2).size

12

## Indexing

Select by index number, index starts with zero "$0$"

In [13]:
arr[0]

0

In [14]:
arr[2]

2

In [15]:
arr[-1]

11

In [16]:
arr[12]

IndexError: index 12 is out of bounds for axis 0 with size 12

2 dimensional array

In [17]:
arr2 = arr.reshape(4, 3)

In [18]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
arr2[0]

array([0, 1, 2])

In [20]:
arr2[-1]

array([ 9, 10, 11])

*Numpy has another syntax for accessing multidimensional array more elegantly*

`arr[row, column]`

In [22]:
arr2[0, 1]

1

*select item from 1st row and 2nd column.*
> *Which is same as `arr[0][1]` but above syntax should be preferrable*

In [25]:
arr2[2, 2]

8

3 - dimensional array

In [26]:
arr3 = arr.reshape(2, 2, 3)

In [27]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [28]:
arr3[1, 0, 1]

7

*select from 2nd depth, 1st row and 2nd column*
> `arr[depth, row, column]`

## Slicing

In [35]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Get all items from 3rd row

In [33]:
arr2[2, :]

array([6, 7, 8])

In [34]:
arr2[2]

array([6, 7, 8])

*empty colon $:$ is redundant here*

Get all items from 2nd column

In [36]:
arr2[:, 1]

array([ 1,  4,  7, 10])

In [15]:
# get all items from 3rd row except first
arr[2, 1:]

array([ 9, 10, 11])

In [16]:
# get all items from 3rd row except last
arr[2, :-1]

array([ 8,  9, 10])

In [17]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
# get all items from 2nd column
arr[:, 1]

array([1, 5, 9])

In [19]:
# get all items from 2nd column except first
arr[1:, 0]

array([4, 8])

In [20]:
# get all items from 2nd column except last
arr[:-1, 1]

array([1, 5])

In [21]:
# get 2nd and 3rd column items from 2nd and 3rd row
arr[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

### Assigning values to array

In [22]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr[0, 0] = 20

In [24]:
arr

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr[1, 1:]

array([5, 6, 7])

In [26]:
arr[1, 1:] = [55, 66, 77]

In [27]:
arr

array([[20,  1,  2,  3],
       [ 4, 55, 66, 77],
       [ 8,  9, 10, 11]])

In [28]:
arr[1:3, 1:3] = [[555, 666], [999, 100]]

In [29]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 666,  77],
       [  8, 999, 100,  11]])

**slices are references**

In [30]:
ab = arr[1, 2:]

In [31]:
ab

array([666,  77])

In [32]:
ab[0] = 667

In [33]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

> *`667` is reflected on `arr`, because `ab` is just a reference to slice of `arr`*

### Three dimensional array

In [34]:
arr3 = np.arange(24).reshape(2, 3, 4)
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

> *`depth, rows, columns`*

**Indexing**

`arr3[depth, row, column]`

In [35]:
arr3[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
arr3[1, 0]

array([12, 13, 14, 15])

In [37]:
arr3[1, 0, 3]

15

**slicing**

In [38]:
arr3[1, 1:, :-1]

array([[16, 17, 18],
       [20, 21, 22]])

In [39]:
arr3[:, 1:, :-1]

array([[[ 4,  5,  6],
        [ 8,  9, 10]],

       [[16, 17, 18],
        [20, 21, 22]]])

### Fancy Indexing

In [40]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [41]:
# select 2nd and 3rd row
arr[[1, 2]]

array([[  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [43]:
# select 1st, 3rd and 4th item of 2nd row
arr[1, [0, 2, 3]]

array([  4, 667,  77])

In [44]:
# select 1st and 4th item of 2nd and 3rd column respectively
arr[[0, -1], [0, -1]]

array([20, 11])

In [45]:
arr[::2, [0, -1]]

array([[20,  3],
       [ 8, 11]])

In [46]:
arr[1, 2]

667

### Boolean operation and Masking

In [47]:
abc = np.arange(30)
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
abc < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False], dtype=bool)

> *gives us boolean array, with True on each element which satifies the condition*

*Only select that satisfy condition*

In [49]:
abc[abc < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
abc[(abc < 10) | (abc > 20)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

use __&__ for "_and_", __|__ for "_or_". Each condition must be enclosed in brackets*

*each condition should be enclosed in brackets, to remove ambiguity created by operator precedence*

In [51]:
abc[abc % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## Numpy Methods

In [52]:
abc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [53]:
# sum of all elements
abc.sum()

435

In [54]:
# product
abc.prod()

0

In [55]:
abc[(abc > 1) & (abc < 10)].prod()

362880

In [63]:
# index of minimum value
abc.argmin()

0

In [64]:
# index of maximum value
abc.argmax()

29

**argmin/argmax in multidimensional array**

In [65]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [66]:
# index of minimum value as if given array is flat
arr.argmin()

1

In [67]:
arr.argmax()

9

In [68]:
np.unravel_index(arr.argmin(), arr.shape)

(0, 1)

In [69]:
np.unravel_index(arr.argmax(), arr.shape)

(2, 1)

In [70]:
help(np.unravel_index)

Help on built-in function unravel_index in module numpy.core.multiarray:

unravel_index(...)
    unravel_index(indices, dims, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``dims``. Before version 1.6.0,
        this function accepted just one index value.
    dims : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
        array.
    
    See Also
    --------
    ravel_multi_index
    

In [71]:
np.unravel_index(6, arr.shape)

(1, 2)

In [72]:
np.unravel_index(6, (4, 2))

(3, 0)

> return tuple is index within multidimensional array, ie. 0th row and 1st column

*sum across rows or across columns*

In [73]:
arr

array([[ 20,   1,   2,   3],
       [  4, 555, 667,  77],
       [  8, 999, 100,  11]])

In [74]:
# across rows
arr.sum(axis=0)

array([  32, 1555,  769,   91])

In [75]:
# across columns
arr.sum(axis=1)

array([  26, 1303, 1118])

*can be used with other methods as well*

In [76]:
arr.mean(axis=1)

array([   6.5 ,  325.75,  279.5 ])